### ISSUE TITLE
Increment initial value not working

### ISSUE THREAD

**Issue by parf** [php-memcached-dev/php-memcached#133]
```
$mc = new Memcached();
#={"class":"Memcached","0":{}}
$mc->addServer('192.168.1.2', 11211);
#=true
# INCREMENT TEST
; $key = "some-key-12346";
$mc->get($key);
#=false
$mc->increment($key, 1, 147);   // set initial value to 147    # ERROR: RETURN VALUE SHOULD BE 147
#=false
$mc->get($key);
#=false
; $mc->set($key, 10, 30);
$mc->increment($key);
#=11
$mc->get($key);
#=11
```

PS:
php-pecl-memcached-2.1.0-8.fc20.x86_64
libmemcached-1.0.16-1.fc20.x86_64

$ php -v 
PHP 5.5.7 (cli) (built: Dec 11 2013 07:38:35) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

**Comment by cedx** [comment]
Version 2.2.0 of Memcached is available in Ubuntu 15.04:
http://packages.ubuntu.com/vivid/php5-memcached

Yes, this is sad to not having it on 14.04 LTS : encountered this bug today :(
