### ISSUE TITLE
Failed to build due to checking for libmemcached location... configure: error: Unable to find memcached.h

### ISSUE THREAD

**Issue by weizhu-us** [php-memcached-dev/php-memcached#140]
I was trying to build php-memcached, 
 ./configure --with-libmemcached-dir=/u/weiz/libmemcached-1.0.16

got the following error
checking for libmemcached location... configure: error: Unable to find memcached.h under /u/weiz/libmemcached-1.0.16

by looking at the 
https://github.com/php-memcached-dev/php-memcached/blob/master/config.m4#L277

It's looking for 
if test ! -f "$PHP_LIBMEMCACHED_DIR/include/libmemcached/memcached.h"; 

I have downloaded libmemcached-1.0.16 and built it.

 find ./ -name memcached.h
./libmemcached-1.0.16/libtest/memcached.h
./libmemcached-1.0.16/libmemcached-1.0/memcached.h
./libmemcached-1.0.16/libmemcached-1.0/struct/memcached.h
./libmemcached-1.0.16/libmemcached/memcached.h

None of them are under /include/ directory. Did I miss anything obvious?

**Comment by winos** [comment]
this worked for me.

you should put the aasolute path of your libmemcached. E.g: 

```
 --with-libmemcached-dir=/usr/local/libmemcached/ --disable-memcached-sasl
```

The scrip config (when you perfom ./config ) contain this line:

```
 if test ! -f "$PHP_LIBMEMCACHED_DIR/include/libmemcached/memcached.h"; then
  278:       AC_MSG_ERROR(Unable to find memcached.h under $PHP_LIBMEMCACHED_DIR)

```

**Comment by emiglobetrotting** [comment]
having the same error

    cd php-memcached
    /etc/php7/bin/phpize
    ./configure --prefix='/etc/php7' --with-libmemcached-dir='/usr' --disable-memcached-sasl  --with-  libdir='/lib/x86_64-linux-gnu' --with-php-config='/etc/php7/bin/php-config'
    make && make install

./configure run successfully, but when i try to make && make install i'm having the error below:

    In file included from /php-src/ext/php-memcached/php_memcached.c:26:0:
    /php-src/ext/php-memcached/php_memcached_private.h:44:40: fatal error:     ext/standard/php_smart_str.h: No such file or directory
     #include <ext/standard/php_smart_str.h>
                                        ^
    compilation terminated.
    make: *** [php_memcached.lo] Error 1

**Comment by mariusz-buk** [comment]
First install libmemcached eg. **sudo yum install libmemcached-devel**

I have memcached.h located in /usr/include/libmemcached.

So I executed ./configure --with-libmemcached-dir=**/usr** --disable-memcached-sasl

I hope this helps anyone.

**Comment by Saneesh** [comment]
> libmemcached-dev for ubuntu18

From where you downloaded it?

**Comment by fabiang** [comment]
For those who are currently trying to build this extension on Debian Bookworm:

```
apt-get install gdebi-core -y \
    && curl --fail \
        http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1n-0+deb10u3_amd64.deb \
        -o /tmp/libssl1.1_1.1.1n-0+deb11u4_amd64.deb \
    && gdebi --non-interactive /tmp/libssl1.1_1.1.1n-0+deb11u4_amd64.deb \
    && curl --fail \
        http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl-dev_1.1.1n-0+deb10u3_amd64.deb \
        -o /tmp/libssl-dev_1.1.1n-0+deb10u3_amd64.deb \
    && gdebi --non-interactive /tmp/libssl-dev_1.1.1n-0+deb10u3_amd64.deb \
    && rm -f /tmp/libssl1.1_1.1.1n-0+deb11u4_amd64.deb /tmp/libssl-dev_1.1.1n-0+deb10u3_amd64.deb 
```
[Based on this answer](https://github.com/nodejs/docker-node/issues/1915#issuecomment-1589387922). Looks like the the libmemcached version in Bookworm only supports OpenSSL 1.x, which was of cause removed from Bookworm. You probably need to adjust the URLs.

**Comment by bagermen** [comment]
package` libssl-dev` is also required for bookworm
