### ISSUE TITLE
Session values greater than 30 days expire immediately.

### ISSUE THREAD

**Issue by ianmaddox** [php-memcached-dev/php-memcached#142]
Sessions with session.gc_maxlifetime greater than 2,592,000 expire immediately because the value is interpreted as a unix timestamp.  Setting a gc_maxlifetime of 2,678,400 (31 days) will result in no sessions being stored because the driver is telling memcached to  expire the key 1970-02-01 12:00:00am UTC.

**Comment by sodabrew** [comment]
Fixed in upcoming release of php-memcached 3.0.0
