### ISSUE TITLE
can't compile 2.2.0 on centos 6 using stock libmemcached 0.31 and php 5.5

### ISSUE THREAD

**Issue by b-harper** [php-memcached-dev/php-memcached#146]
Hey everyone,

I am running into issues attempting to compile 2.2.0 on centos 6 using libmemcached 0.31 and php 5.5.  See the following gist for the console output:

https://gist.github.com/b-harper/f4a70f87f1d021354f1e

Looking over the change log, I see that 0.X is supported again.  There are a few issues that have similar errors and sometime mention libmemcached 0.31 but it is not clear if this issue have been corrected for such an old version of libmemcached.  

Any ideas on what I can do to work through this issue?

**Comment by sodabrew** [comment]
Closing, libmemcached 0.3x isn't supported.
