### ISSUE TITLE
PHP 7.0 / PHPNG support

### ISSUE THREAD

**Issue by centminmod** [php-memcached-dev/php-memcached#171]
I am curious how far off if planned, is PHP 7 (PHPNG) support for memcached PHP extension https://wiki.php.net/phpng-upgrading ?

I am using PHP 7.0.0-dev with CentOS 7.1 for my Wordpress blog at http://wordpress7.centminmod.com/162/wordpress-blog-update-to-centos-7-1-1503-php-7-0-0-dev/ just missing memcached PHP extension support :)

cheers

**Comment by Gasol** [comment]
Check out the php7 branch, taste it and help to test.

**Comment by jmalinens** [comment]
compilled memcached and got this error: PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/remi/php70/root/usr/lib64/php/modules/memcached.so' - /opt/remi/php70/root/usr/lib64/php/modules/memcached.so: undefined symbol: ZEND_CTOR_MAKE_NULL in Unknown on line 0

**Comment by centminmod** [comment]
thanks @Gasol managed to compile it fine for PHP 7.0.0-dev although did get this some warnings during make will post a separate issue for it

**Comment by anthonyryan1** [comment]
A more useful printout of @jmalinens reported issue there is:
```
php_memcached.c:411:3: warning: implicit declaration of function ‘ZEND_CTOR_MAKE_NULL’ [-Wimplicit-function-declaration]
```

**Comment by krakjoe** [comment]
Work is well under way ... so closing ...
