### ISSUE TITLE
php7 php-memcached branch make warnings --enabled-memcached-json

### ISSUE THREAD

**Issue by centminmod** [php-memcached-dev/php-memcached#172]
when configured with `--enable-memcached-json` i get the following during make stage

    /svr-setup/memcached-php7/php_memcached.c: In function ‘s_unserialize_value’:
    /svr-setup/memcached-php7/php_memcached.c:3335:4: warning: passing argument 2 of ‘php_json_decode’ discards ‘const’ qualifier from pointer target type [enabled by default]
        php_json_decode(value, payload, payload_len, (serializer == SERIALIZER_JSON_ARRAY), JSON_PARSER_DEFAULT_DEPTH);
        ^
    In file included from /svr-setup/memcached-php7/php_memcached.c:41:0:
    /usr/local/include/php/ext/json/php_json.h:101:20: note: expected ‘char *’ but argument is of type ‘const char *’
     static inline void php_json_decode(zval *return_value, char *str, int str_len, zend_bool assoc, zend_long depth)

my configure options

    ./configure --with-php-config=/usr/local/bin/php-config --enable-memcached-json --with-libmemcached-dir=/usr

although it seems to turn up fine after make install

    php --ri memcached
    
    memcached
    
    memcached support => enabled
    Version => 2.2.0
    libmemcached version => 1.0.16
    SASL support => yes
    Session support => yes
    igbinary support => no
    json support => yes
    msgpack support => no
    
    Directive => Local Value => Master Value
    memcached.sess_locking => 1 => 1
    memcached.sess_consistent_hash => 0 => 0
    memcached.sess_binary => 0 => 0
    memcached.sess_lock_wait => 150000 => 150000
    memcached.sess_lock_max_wait => 0 => 0
    memcached.sess_lock_expire => 0 => 0
    memcached.sess_prefix => memc.sess.key. => memc.sess.key.
    memcached.sess_number_of_replicas => 0 => 0
    memcached.sess_randomize_replica_read => 0 => 0
    memcached.sess_remove_failed => 0 => 0
    memcached.sess_connect_timeout => 3000 => 3000
    memcached.sess_sasl_username => no value => no value
    memcached.sess_sasl_password => no value => no value
    memcached.compression_type => fastlz => fastlz
    memcached.compression_factor => 1.3 => 1.3
    memcached.compression_threshold => 2000 => 2000
    memcached.serializer => php => php
    memcached.use_sasl => 0 => 0
    memcached.store_retry_count => 2 => 2

build

    php -v
    PHP 7.0.0-dev (cli) (built: Apr  8 2015 11:54:10) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by krakjoe** [comment]
Warnings gone in php7 branch.
