### ISSUE TITLE
When will the session lock be released?

### ISSUE THREAD

**Issue by huangyg11** [php-memcached-dev/php-memcached#176]
I use memcached as php session handler.  Recently, I find the request often spend 30s to respond.  I strace the process, and find it is blocked by the session lock. When I request the site first time, it lock the session. And when requesting in the second time, the lock is still acquired, causing the request wait until the 30s timeout.

I check the source, and find `php_memc_sess_unlock` function. But I haven't find where it is been called?

**Comment by sodabrew** [comment]
Closing this as #269 has a lot of great discussion on setting the session lock values.
