### ISSUE TITLE
JSON test failures

### ISSUE THREAD

**Issue by krakjoe** [php-memcached-dev/php-memcached#181]
When JSON is used as a serializer types_json.phpt fails.

**Comment by krakjoe** [comment]
So I had a bit of time to dig this evening ... it turns out that php_json_encode relies on global state (module globals), which is quite terrible, but worse, we did not export the global id in zts or struct in nts ... rendering json pretty unreliable from outside ... I fixed that in php-src ...

Still, the extension is behaving quite strangely ... still investigating ...

**Comment by HMAZonderland** [comment]
How's this going?

**Comment by sodabrew** [comment]
I cannot reproduce this, the test passes now.
