### ISSUE TITLE
Create release for PHP 7 support

### ISSUE THREAD

**Issue by ablyler** [php-memcached-dev/php-memcached#185]
Any chance a beta release could be created to support PHP 7?  I know there is a branch, but a released version would help us in homebrew-php (https://github.com/Homebrew/homebrew-php/pull/2051).  Thanks!

**Comment by carlwgeorge** [comment]
I noticed this issue was created before the [final PHP 7.0.0 release](http://php.net/archive/2015.php#id2015-12-03-1).  Now that PHP7 is stable, can anyone comment on the overall progress of this?  I can see that there are several open issues mentioning PHP7, but I don't fully grasp the severity of each.

For context, I would like to [create RPM packages](https://github.com/iuscommunity/wishlist/issues/34) for the [IUS](https://ius.io) repository built against our php70u packages.

**Comment by matts2cant** [comment]
A new stable release would really help everyone using heroku. They won't add this extension for php7 otherwise.

**Comment by jonathanpmartins** [comment]
php-memcached stable is the only reason because I don't upgrade to php7. After that I will be able to go well...

**Comment by hydrapolic** [comment]
Yes, would be great to package this thing for Gentoo Linux :)

**Comment by mkoppanen** [comment]
Hey,

I merged my own PR a few minutes ago, which resolves some PHP7 issues. There is a minor backwards compatibility break with user flags, which is unavoidable.  

Can you please give php7 branch a spin with your existing code to see if there are any last minute issues to fix before rolling out beta.

**Comment by hydrapolic** [comment]
@mkoppanen - a test run on Gentoo Linux with PHP 7.0.3_rc1

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   51
---------------------------------------------------------------------

Number of tests :  121               110
Tests skipped   :   11 (  9.1%) --------
Tests warned    :    1 (  0.8%) (  0.9%)
Tests failed    :    3 (  2.5%) (  2.7%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :  106 ( 87.6%) ( 96.4%)
---------------------------------------------------------------------
Time taken      :   23 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Session basic open, write, destroy [tests/session_basic.phpt]
Session basic open, write, destroy [tests/session_basic2.phpt]
Session basic open, write, destroy [tests/session_basic3.phpt]
=====================================================================

=====================================================================
WARNED TEST SUMMARY
---------------------------------------------------------------------
Memcached store, fetch & touch expired key [tests/expire.phpt] (warn: XFAIL section but test passes)
=====================================================================

**Comment by mkoppanen** [comment]
@hydrapolic,

thanks for that. Pushed fixes for session functionality and looks like tests pass. I would be most curious if the session functionality actually works in web environment.

**Comment by VincentSurelle** [comment]
Can anyone give a date (Approximate) for PECL package release ?
Thanks for your work

**Comment by mkoppanen** [comment]
@VincentSurelle,

I would guess within a week. There are some open issues that I am tackling at the moment (some require larger changes and backwards compatibility breaks) so it will more than likely be a major version bump.

**Comment by jonathanpmartins** [comment]
:+1:

**Comment by VincentSurelle** [comment]
@mkoppanen,
Nice !
Great work guys !

**Comment by mkoppanen** [comment]
Ok, I started to look at this more on Friday and kept finding a lot of code that just wasn't right. PR #211 resolves quite a few issues and it looks like beta can go out tomorrow. 

All tests that are expected to pass now are passing. Even igbinary works!

**Comment by ralfbecker** [comment]
Any news on a php 7 supporting release?

**Comment by codegrau** [comment]
Would appreciate news for php7 support.

**Comment by jonathanpmartins** [comment]
@codegrau You can compile it from the php7 branch. I show an example here: https://github.com/php-memcached-dev/php-memcached/issues/194#issuecomment-193823540.
Some test are failing yet, but my basic unit test PASS. Give a try, it works fine, but it not 100% ready to production.

**Comment by matts2cant** [comment]
@mkoppanen: Do you have a date in mind as to when we can expect a new version to be officially released ?

Thank you

**Comment by sint** [comment]
Any news? Thanks for your work!

**Comment by fpswebmaster** [comment]
Any update on this ?

**Comment by holobyte** [comment]
Is there a general timeframe for a release? Any update(s) would be appreciated.

**Comment by ullrichp** [comment]
Would like to leave my bump here as well. Is there anything i, we, the pope or anybody can do to get this issue closed? Thanks for the work!

**Comment by holobyte** [comment]
I realize this upgrade is complicated and thank the developers for their work but please can we could get some kind of expected timeframe -- we would all sincerely appreciate it.

**Comment by jonathanpmartins** [comment]
@holobyte like I just said. I migrate my caches to Redis. No problems until now...
My tip? Go with redis! PHP 7.1 is to be released soon...go with redis! ehhhh

**Comment by hydrapolic** [comment]
Pecl-redis has a release for PHP 7.0, that's true, however we didn't have problems taking the last commit from php7 branch of pecl-memcached either.

**Comment by carlwgeorge** [comment]
The lack of maintainer response here does not inspire confidence in the status of this project.

**Comment by sodabrew** [comment]
I'm a new maintainer here. I'm listening, and working through open tickets, and a release, yes that's on the radar.

**Comment by carlwgeorge** [comment]
That's awesome to hear @sodabrew.  Don't be afraid to create alpha and beta releases prior to a stable release.  It helps everyone (maintainers, packagers, and users).

**Comment by sodabrew** [comment]
The 3.0.0 release will be released Real Soon Now. I'm cleaning up the tickets in preparation.

**Comment by holobyte** [comment]
Thanks for your work @sodabrew! I look forward to the 3.0 release.
