### ISSUE TITLE
PHP ini settings > alignment with legacy memcache (non-d)

### ISSUE THREAD

**Issue by bryanlatten** [php-memcached-dev/php-memcached#187]
Hey guys,
I'm working on a long-overdue upgrade strategy from the legacy memcache extension to memcached. I noticed that several (important) .ini settings available in the legacy extension are only exposed at runtime, and for the ones that *do* exist in .ini form, are prefixed with `sess_`, leading me to believe it only takes when set as a session handler. My eventual goal would be to run them interchangeably for a short period of time during a cutover. Any advice would be appreciated!

| Memcache(legacy) | Memcached | Note |
| --------------------------|------------------|--------|
| `memcache.hash_function => crc32 => crc32` | n/a | - |
| `memcache.hash_strategy => consistent => consistent` | `memcached.sess_consistent_hash => 0 => 0` | does it apply beyond sessions? |
| `memcache.protocol => ascii => ascii` | `memcached.sess_binary => 0 => 0`| does it apply beyond sessions? |

**Comment by mkoppanen** [comment]
sess_ prefixed keys only apply to sessions.

**Comment by bryanlatten** [comment]
@mkoppanen thanks for the reply --- are there any ini settings that *dont* just apply to sessions?

**Comment by mkoppanen** [comment]
The following ones:
```
; Set the compression type
; valid values are: fastlz, zlib
; the default is fastlz
memcached.compression_type = "fastlz"

; Compression factor
; Store compressed value only if the compression
; factor (saving) exceeds the set limit.
;
;  store compressed if:
;    plain_len > comp_len * factor
;
; the default value is 1.3 (23% space saving)
memcached.compression_factor = "1.3"

; The compression threshold
;
; Do not compress serialized values below this threshold.
; the default is 2000 bytes
memcached.compression_threshold = 2000

; Set the default serializer for new memcached objects.
; valid values are: php, igbinary, json, json_array, msgpack
;
; json - standard php JSON encoding. This serializer
;        is fast and compact but only works on UTF-8
;        encoded data and does not fully implement
;        serializing. See the JSON extension.
; json_array - as json, but decodes into arrays
; php - the standard php serializer
; igbinary - a binary serializer
; msgpack - a cross-language binary serializer
;
; The default is igbinary if available, then msgpack if available, then php otherwise.
memcached.serializer = "igbinary"

; Use SASL authentication for connections
; valid values: On, Off
; the default is Off
memcached.use_sasl = Off

; The amount of retries for failed store commands.
; This mechanism allows transparent fail-over to secondary servers when
; set/increment/decrement/setMulti operations fail on the desired server in a multi-server
; environment.
; the default is 2
memcached.store_retry_count = 2
```

**Comment by bryanlatten** [comment]
Sorry @mkoppanen, I meant, is there any `.ini` way to configure hash_function, hash_strategy, and protocol, or is it always at object construction time?

**Comment by mkoppanen** [comment]
@bryanlatten,

it can be set during the lifetime of the object using memcached->setOption(s). There is no ini-setting for defaults

**Comment by bryanlatten** [comment]
Seems strangely missing though, right? Can I make a feature request? Would be great to enforce this before runtime

**Comment by mkoppanen** [comment]
Sure, create a ticket and I'll take a look at it.
