### ISSUE TITLE
php_memc_*_impl wrongly return MEMCACHED_BAD_KEY_PROVIDED when whitespace in key in binary mode

### ISSUE THREAD

**Issue by dfuhry** [php-memcached-dev/php-memcached#188]
The php_memcached.c php_memc_*_impl() functions perform the below check, which is correct in non-binary mode, but incorrect in binary mode:
    if (key_len == 0 || strchr(key, ' ')) {
       i_obj->rescode = MEMCACHED_BAD_KEY_PROVIDED;
       RETURN_FALSE;
    }
In binary mode, spaces are allowed in keys, so the strchr call should be skipped.

Also to be completely correct for non-binary mode, I guess it should check for any whitespace character (tab, etc.; not just space). I do not care about this last point for my current purposes though.

**Comment by mkoppanen** [comment]
Fixed in php7 branch
