### ISSUE TITLE
It is not work in PHP7 RC5

### ISSUE THREAD

**Issue by mydansun** [php-memcached-dev/php-memcached#192]
I meet this problem:

/opt/php-memcached-php7/php_memcached_private.h:44:40: error: ext/standard/php_smart_str.h: No such file or directory

I found the php_smart_str.h has been removed in my build.

**Comment by matipl-pl** [comment]
@mydansun: I can compile php-memcached-php7 for PHP 7 RC6.

> /usr/local/php70/bin/phpize
> ./configure \
> --disable-memcached-sasl \
> --with-php-config=/usr/local/php70/bin/php-config
> make
> make install

**Comment by mydansun** [comment]
thanks

**Comment by mkoppanen** [comment]
Resolved
