### ISSUE TITLE
Problem with PHP 7 RC6 + igbinary

### ISSUE THREAD

**Issue by matipl-pl** [php-memcached-dev/php-memcached#193]
I cannot compile php-memcached-php7 with --enable-memcached-igbinary flag.
Without "--enable-memcached-igbinary" works correctly.

> /usr/local/php70/bin/phpize
> ./configure \
> --disable-memcached-sasl \
> --enable-memcached-igbinary \
> --with-php-config=/usr/local/php70/bin/php-config
> make

Make response error:
> php_memcached.c:3083:44: error: ‘smart_str’ has no member named ‘c’
>    if (igbinary_serialize((uint8_t **) &buf->c, &buf->len, value) != 0) {
>
> php_memcached.c:3083:53: error: ‘smart_str’ has no member named ‘len’
>    if (igbinary_serialize((uint8_t **) &buf->c, &buf->len, value) != 0) {

**Comment by TysonAndre** [comment]
This was fixed months ago, and can be closed
