### ISSUE TITLE
Problem with new version memcached-1.4.24

### ISSUE THREAD

**Issue by ali88code** [php-memcached-dev/php-memcached#203]
I have installed memcached ,php-pecl-memcached and libmemcached.
 1.memcached (1.4.24)
 2.php5.5.30  , php-pecl-memcached (2.2.0)
 3.libmemcached(1.0.18)

I try  with  php script  test.php
<?php
$mc = new Memcached();
$mc->addServer('127.0.0.1',11211);
$stats = $mc->getAllKeys();
echo "Return code:", $mc->getResultCode()."\n";
echo "Retucn Message:", $mc->getResultMessage () ."\n";
print_r ($stats);
?>
Return code:9
Retucn Message:CLIENT ERROR

I look the log on memcached server log
 <36 stats cachedump 57 0
 <36 stats cachedump 58 0
 <36 stats cachedump 59 0
 <36 stats cachedump 60 0
 <36 stats cachedump 61 0
 <36 stats cachedump 62 0
 <36 stats cachedump 63 0

> 36 CLIENT_ERROR Illegal slab id
>  <36 quit
>  <36 connection closed.

I  change to memcached version 1.4.15 ,and try php script test.php

   Return code:0
   Retucn Message:SUCCESS
   Array
  (
       [0] => qinyao
       [1] => andy
    )

**Comment by scottchiefbaker** [comment]
I came here to report the same thing. This bug should be be changed from "Problem with new version memcached-1.4.24" to "getAllKeys() fails with result code 9" as it's more descriptive and will help the developer categorize things better.

I'm running PHP 7.0.5 and memcached 1.4.25 and I'm getting the same error.

`getAllKeys()` returns false
`getResultCode()` returns 9
`getResultMessage()` returns CLIENT ERROR

**Comment by DerDu** [comment]
Same here..

Error: 9 - CLIENT ERROR

PHP Version 7.0.4-7ubuntu2 (16.04 LTS)
php-memcached compiled from git today (24 May 2015)

**Comment by billynoah** [comment]
Same problem here.  If anyone has a workaround other than going to an older version of memcached please post.

**Comment by andrewnicols** [comment]
Still an issue on memcached 1.4.33.
It looks like this issue first appeared in 1.4.23.

Causes major issues for us.

**Comment by andrewnicols** [comment]
This is actually a bug in libmemcached: https://bugs.launchpad.net/libmemcached/+bug/1534062

**Comment by Mattie112** [comment]
Oh yes that bug, took quite some time to find that issue. If everybody can mark that issue as "this affects me" (top left) then I hope I will finally get a reply on it!

**Comment by andrewnicols** [comment]
Given the last release of libmemcached was two years ago, I'm not holding out much hope I admit :/

I've just proposed an alternate fix route, but I've not written c for many years so I'm unlikely to e able to work on this myself.

**Comment by Mattie112** [comment]
Well yes, I noticed that already when submitting that bug :p Still hoping that someday it will be fixed, for now using 1.4.22 just works fine for us.

**Comment by sodabrew** [comment]
Good find! We should be able to work around this in the client code php-memcached.

**Comment by nadavkav** [comment]
This causes major issues for us too.
Can any core developer confirm it and give any status about this?
It would be very much appreciated

**Comment by sodabrew** [comment]
@nadavkav https://github.com/php-memcached-dev/php-memcached/issues/203#issuecomment-257572897

**Comment by nadavkav** [comment]
@sodabrew , are you php-memcached core developer?

**Comment by sodabrew** [comment]
Yes, I'm a member of this repo. Sorry for the curt note, here's a longer explanation:

A quick read of the libmemcached code suggests that the `CLIENT_ERROR` status comes back from libmemcached after php-memcached has already processed the return data callbacks. I need to verify this, and then ignore the particular error in the event that we've already got data in-hand.

**Comment by nadavkav** [comment]
Great! thank you very much for the quick reply and explanation of the possible cause for this issue.

**Comment by Mattie112** [comment]
Ah great, I've only reported it at libmemcached, never thought of reporting it here :) But thanks!

**Comment by comensee** [comment]
Hi people,
Any updates about this issue ?
Thanks

**Comment by sodabrew** [comment]
@comensee Yes, this is the most recent status: https://github.com/php-memcached-dev/php-memcached/issues/203#issuecomment-258606958

**Comment by tibor78** [comment]
Hi Aaron,

have you been able to fix it? last comment from Nov 2016 is unclear about if its fixed or not. 

We cant use memcached 1.4.24+ for more than one year, sadly AWS and others do not allow versions < 1.4.24 anymore so we cant use memcached anymore.

:)

**Comment by sodabrew** [comment]
I haven't started work on this issue yet. "Soon" - I'm putting together some important fixes for the next minor release already!

**Comment by alasdairdc** [comment]
still an issue on debian version php-memcached (3.0.1+2.2.0-1)

**Comment by scottchiefbaker** [comment]
This isn't fixed until 3.0.3.

**Comment by alasdairdc** [comment]
[correction] it does appear to work in 3.0.1
