### ISSUE TITLE
PHP 7: Declaration mismatch (::get, ::getMulti)

### ISSUE THREAD

**Issue by kakserpom** [php-memcached-dev/php-memcached#205]
`php7 -r 'class MemcachedLog extends Memcached {public function get( $key, $cache_cb = null, &$cas_token = null, &$udf_flags = null ) {}}'`
PHP Warning:  Declaration of MemcachedLog::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL) should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL) in Command line code on line 1

**Comment by SjonHortensius** [comment]
This is already reported as #126 

PHP7 increases the importance of this issue, as it has become a lot harder to ignore this warning

**Comment by mkoppanen** [comment]
Fixed in php7 branch
