### ISSUE TITLE
PHP7 Error - undefined symbol: memcached_destroy_sasl_auth_data

### ISSUE THREAD

**Issue by christophe-mailfert** [php-memcached-dev/php-memcached#217]
With the last version of PHP7 branch, after make install and add memcached.so in php ini fil i got:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/memcached.so' - /usr/lib64/php/modules/memcached.so: undefined symbol: memcached_destroy_sasl_auth_data in Unknown on line 0

The only way for works was to checkout revision 7cb0c48c8da8fbcfdd04350338d6ebef15ddcd14

Any idea ?

**Comment by mkoppanen** [comment]
Hey,

Can you tell me which version of libmemcached are you using?

**Comment by mkoppanen** [comment]
I just merged a large PR so can you give the latest php7 branch a go and report back?

**Comment by mkoppanen** [comment]
this has been fixed with #219

**Comment by jonathanpmartins** [comment]
:+1:
