### ISSUE TITLE
PHP7 Error -  fatal error: ext/standard/php_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by moryxsw** [php-memcached-dev/php-memcached#218]
After I run "./configure" ,I find It's "configure: creating ./config.status config.status: creating config.h config.status: executing libtool commands" .Though I run " ./configure --with-libmemcached-dir=/usr/share/libmemcached  --disable-memcached-sasl" (of course ,I run "find / -name libmemcached" ,the road is "/usr/share/libmemcached".)  When I run "make" ,It's 
"In file included from /home/y9/php-memcached-php7/php_memcached.c:26:0:
/home/y9/php-memcached-php7/php_memcached_private.h:44:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
compilation terminated.
Makefile:194: recipe for target 'php_memcached.lo' failed
make: *** [php_memcached.lo] Error 1"
can you tell me the reason? thank you

**Comment by mkoppanen** [comment]
@moryxsw,

The reason is more than likely that you have PHP7 and you are not using the current php7 branch of php-memcached.

**Comment by zhangqianvvw** [comment]
[root@iZ239flpdfbZ php-memcached]# make
/bin/sh /soft/php-memcached/php-memcached/libtool --mode=compile cc -I/usr/local/php/include/php    -I. -I/soft/php-memcached/php-memcached -DPHP_ATOM_INC -I/soft/php-memcached/php-memcached/include -I/soft/php-memcached/php-memcached/main -I/soft/php-memcached/php-memcached -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/lib/libmemcached/include  -DHAVE_CONFIG_H  -g -O2   -c /soft/php-memcached/php-memcached/php_memcached.c -o php_memcached.lo 
mkdir .libs
 cc -I/usr/local/php/include/php -I. -I/soft/php-memcached/php-memcached -DPHP_ATOM_INC -I/soft/php-memcached/php-memcached/include -I/soft/php-memcached/php-memcached/main -I/soft/php-memcached/php-memcached -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/lib/libmemcached/include -DHAVE_CONFIG_H -g -O2 -c /soft/php-memcached/php-memcached/php_memcached.c  -fPIC -DPIC -o .libs/php_memcached.o
In file included from /soft/php-memcached/php-memcached/php_memcached.c:26:0:
/soft/php-memcached/php-memcached/php_memcached_private.h:44:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
                                        ^
compilation terminated.
make: *** [php_memcached.lo] Error 1

**Comment by EugenMayer** [comment]
this happens only if master is used, branch php7 works and fixes this - verified

**Comment by krakjoe** [comment]
This is a misconfiguration issue.

Ensure you are using the correct ```phpize```, and the correct ```--with-php-config``` option to ```./configure```.

**Comment by onassar** [comment]
Running into this now. A bit confused as to how to resolve.

**Comment by sodabrew** [comment]
Use the released php-memcached 3.0.x version. Your screenshot indicates building the 2.x version with PHP 7.x and that won’t work.

**Comment by onassar** [comment]
gr8 ill give that a go. thanks!

**Comment by wapmorgan** [comment]
> Use the released php-memcached 3.0.x version. Your screenshot indicates building the 2.x version with PHP 7.x and that won’t work.

3.0.8 does not work with php 7 too
```
/bin/bash /tmp/pear/temp/pear-build-defaultuserbDiJab/memcache-3.0.8/libtool --mode=compile cc -I/usr/local/include/php -I. -I/tmp/pear/temp/memcache -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserbDiJab/memcache-3.0.8/include -I/tmp/pear/temp/pear-build-defaultuserbDiJab/memcache-3.0.8/main -I/tmp/pear/temp/memcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/memcache/memcache.c -o memcache.lo
mkdir .libs
 cc -I/usr/local/include/php -I. -I/tmp/pear/temp/memcache -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuserbDiJab/memcache-3.0.8/include -I/tmp/pear/temp/pear-build-defaultuserbDiJab/memcache-3.0.8/main -I/tmp/pear/temp/memcache -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/memcache/memcache.c  -fPIC -DPIC -o .libs/memcache.o
In file included from /tmp/pear/temp/memcache/php_memcache.h:34:0,
                 from /tmp/pear/temp/memcache/memcache.c:30:
/tmp/pear/temp/memcache/memcache_pool.h:45:47: fatal error: ext/standard/php_smart_str_public.h: No such file or directory
 #include "ext/standard/php_smart_str_public.h"
                                               ^
compilation terminated.
make: *** [Makefile:193: memcache.lo] Error 1
```

**Comment by sodabrew** [comment]
PHP 7.3 support is not released yet. 3.0.8 supports PHP 7.0 - 7.2.

**Comment by wapmorgan** [comment]
Its 7.0.33

**Comment by sodabrew** [comment]
Correction, the current version is 3.0.4. The extension you are used, memcache 3.0.8, is ancient and not support and is not the code in this repository. This one is `memcached`.

**Comment by wapmorgan** [comment]
Oh, my bad. Thanks for explanation.

**Comment by 001101** [comment]
Getting the error when running it with php 7.2 pecl installer, also on 3.0.4 and 3.0.8 version:

command:  /opt/remi/php72/root/usr/bin/pecl install memcache-3.0.4


running: make
/bin/sh /var/tmp/pear-build-rootPYMpuO/memcache-3.0.4/libtool --mode=compile cc -I/opt/remi/php72/root/usr/include/php -I. -I/var/tmp/memcache -DPHP_ATOM_INC -I/var/tmp/pear-build-rootPYMpuO/memcache-3.0.4/include -I/var/tmp/pear-build-rootPYMpuO/memcache-3.0.4/main -I/var/tmp/memcache -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /var/tmp/memcache/memcache.c -o memcache.lo
libtool: compile:  cc -I/opt/remi/php72/root/usr/include/php -I. -I/var/tmp/memcache -DPHP_ATOM_INC -I/var/tmp/pear-build-rootPYMpuO/memcache-3.0.4/include -I/var/tmp/pear-build-rootPYMpuO/memcache-3.0.4/main -I/var/tmp/memcache -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /var/tmp/memcache/memcache.c  -fPIC -DPIC -o .libs/memcache.o
In file included from /var/tmp/memcache/php_memcache.h:34:0,
                 from /var/tmp/memcache/memcache.c:30:
/var/tmp/memcache/memcache_pool.h:33:47: fatal error: ext/standard/php_smart_str_public.h: No such file or directory
 #include "ext/standard/php_smart_str_public.h"
                                               ^
compilation terminated.
make: *** [memcache.lo] Error 1
ERROR: `make' failed

----------------

running: make
/bin/sh /var/tmp/pear-build-rootapZ1Lo/memcache-3.0.8/libtool --mode=compile cc -I/opt/remi/php72/root/usr/include/php -I. -I/var/tmp/memcache -DPHP_ATOM_INC -I/var/tmp/pear-build-rootapZ1Lo/memcache-3.0.8/include -I/var/tmp/pear-build-rootapZ1Lo/memcache-3.0.8/main -I/var/tmp/memcache -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /var/tmp/memcache/memcache.c -o memcache.lo
libtool: compile:  cc -I/opt/remi/php72/root/usr/include/php -I. -I/var/tmp/memcache -DPHP_ATOM_INC -I/var/tmp/pear-build-rootapZ1Lo/memcache-3.0.8/include -I/var/tmp/pear-build-rootapZ1Lo/memcache-3.0.8/main -I/var/tmp/memcache -I/opt/remi/php72/root/usr/include/php -I/opt/remi/php72/root/usr/include/php/main -I/opt/remi/php72/root/usr/include/php/TSRM -I/opt/remi/php72/root/usr/include/php/Zend -I/opt/remi/php72/root/usr/include/php/ext -I/opt/remi/php72/root/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /var/tmp/memcache/memcache.c  -fPIC -DPIC -o .libs/memcache.o
In file included from /var/tmp/memcache/php_memcache.h:34:0,
                 from /var/tmp/memcache/memcache.c:30:
/var/tmp/memcache/memcache_pool.h:45:47: fatal error: ext/standard/php_smart_str_public.h: No such file or directory
 #include "ext/standard/php_smart_str_public.h"
                                               ^
compilation terminated.
make: *** [memcache.lo] Error 1
ERROR: `make' failed

**Comment by Guilherme-Valle** [comment]
@001101 

Same issue here, but with php_intl.lo. Have you fixed it?

**Comment by rprice-adsk** [comment]
Saw on another site: `pecl install memcached` -- note the "d".

**Comment by 001101** [comment]
I mean normally i keep an eye of this, think was too late and my eyes a bit lazy.
But someone really has to starting the project to purge this damn memcache (without d) from the internet!!

**Comment by naseathsaly** [comment]
There is a fix in this link: https://serverpilot.io/docs/how-to-install-the-php-memcache-extension
