### ISSUE TITLE
The get function in php7 memcached extension.

### ISSUE THREAD

**Issue by ambjlon** [php-memcached-dev/php-memcached#221]
I used the get function in php7 memcached extensions as followed(old code work in php5):
 `$cache_cb = NULL, &$cas_token = ''`
`$ret = parent::get($key , $cache_cb , &$cas_token);`
And  I get an error:
**PHP Parse error:  syntax error, unexpected '&'**
Then I modified the code as:
`
$ret = parent::get($key );
`
This time, it worked well.
But I don’t want to modify the old code.
How to   modify  php7 memcached extension to make the old code work well?

**Comment by NoodlesNZ** [comment]
This is not an issue with the extension, nor can it be fixed with the extension. Check http://php.net/manual/en/language.references.pass.php. You only need the & on the function definition and won't work on a parameter when you call the function (as you found out)

**Comment by mkoppanen** [comment]
In addition to that the cas parameter has been removed from get / getMulti methods. It was causing issues with inheritance and needed to go.

**Comment by malkusch** [comment]
> In addition to that the cas parameter has been removed from get / getMulti methods.

What is the alternative then?
