### ISSUE TITLE
Please tag 3.0.0b1

### ISSUE THREAD

**Issue by oerdnj** [php-memcached-dev/php-memcached#225]
Could you please (annotated) tag the 3.0.0b1 release so we can get better version number when using git describe to version the PHP 7 progress? Thanks

**Comment by jonathanpmartins** [comment]
:+1:

**Comment by mkoppanen** [comment]
There is not release for PHP7 yet.

**Comment by oerdnj** [comment]
@mkoppanen I know, but people around the world are using the current git snapshot nonetheless.

**Comment by pcambra** [comment]
As the issue referenced above, this package has been moved to status "unmaintained" in Alpine so it is not available to install from there, the main reason being not having a release to reference in the build. Could we have a release tagged so we can fix it back in there?

**Comment by aleksijohansson** [comment]
+1, a tag would be really helpful! One can create tags without a release. They will be shown on the releases page, but more subtle and they are not called releases.

**Comment by sodabrew** [comment]
The 3.0.0 release will be released Real Soon Now. I'm cleaning up the tickets in preparation.
