### ISSUE TITLE
Add version to documentation

### ISSUE THREAD

**Issue by SpacePossum** [php-memcached-dev/php-memcached#227]
At PECL all package pages ([exampe](https://pecl.php.net/package/memcached/2.2.0RC1)) link to: http://php.net/memcached

There is the documentation of only one version (not sure which one). It would be more useful to have a full API listing for each version of Memcached as to see what method (signatures) are changed between versions.

**Comment by mkoppanen** [comment]
@SpacePossum,

contributions at this front would be more than welcome. I simply swamped and it seems I cannot dedicate huge amounts of time to this.

**Comment by SpacePossum** [comment]
I understand :)
Like to help out, could you give some pointers about how the docs are generated now and where these are at github?

**Comment by krakjoe** [comment]
The PHP manual doesn't support that.

You document the current release, keep a changelog, and put warnings/notes in where necessary.

Anyone can edit the PHP documentation by logging in at ```http://edit.php.net```.

If you decide to work on the documentation, and need somebody to review and commit your changes, please open a new issue, stating the user name you used to make the changes.
