### ISSUE TITLE
Values stored in Memcached influence variables defined in PHP

### ISSUE THREAD

**Issue by yuri-popoff** [php-memcached-dev/php-memcached#228]
Hello!

I have two files:

<?php
// a.php

$o_memcache = new \Memcached();
$o_memcache->set('key','arbitrary_variable_name',0);

include_once('b.php');
b();

?>

<?php
// b.php

function b()
{
  $arbitrary_variable_name = 10;
  var_dump([
    $arbitrary_variable_name
  ]);
}

?>

When I try to run it under CLI, I get error:

[root@s6 q]# php a.php
PHP Notice:  Undefined variable: arbitrary_variable_name in /home/wl/.htprivate/options/q/b.php on line 7
array(1) {
  [0]=>
  NULL
}

Error does not occur if I change name of the variable, or value stored in Memcached.

PHP 7.0.3 (cli) (built: Feb  4 2016 08:51:10) ( NTS )
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
libmemcached-1.0.18
Memcached extension sources are downloaded from php7 branch.

**Comment by yuripave** [comment]
I had similar issue with latest commit in php7 branch https://github.com/php-memcached-dev/php-memcached/commit/52c644be2275f837a42c364f86dcf8592c81f679 via dotdeb https://github.com/gplessis/dotdeb-php-memcached/releases/tag/upstream%2F2.2.0-2-52c644b

I cannot reproduce with a test script yet but the issue is causing unexpected userland variable behavior:
```
$memcache = new \Memcached();
$memcache->addServer('localhost', 11211);
$json_from_memcached = $memcache->get('json'); // a valid json saved earlier
json_decode($json_from_memcached, true); // null, expected to be array
$json_literal = '{"valid":"json"}'; // same content as $json_str but not retrieved from memcache
json_decode($json_literal, true); // array
md5($json_from_memcached) == md5($json_literal); // true
```

I can confirmed last dotdeb release has no such issue.
https://github.com/gplessis/dotdeb-php-memcached/releases/tag/upstream%2F2.2.0-1-7cb0c48
which is on https://github.com/php-memcached-dev/php-memcached/commit/7cb0c48c8da8fbcfdd04350338d6ebef15ddcd14.

**Comment by krakjoe** [comment]
I am not able to reproduce this issue with the latest 7.0, or 7.1.

Can anyone else?

**Comment by yuripave** [comment]
Sadly I am unable to reproduce in non-production environment and do not have time to test latest `php7` branch. Our production is running fine with https://github.com/php-memcached-dev/php-memcached/commit/52c644be2275f837a42c364f86dcf8592c81f679, thanks!

**Comment by dictcp** [comment]
for @yuripave case, it should be the same as https://github.com/php-memcached-dev/php-memcached/issues/250

**Comment by thias** [comment]
Both #250 and #252 are closed, so this issue could probably be closed too now.

**Comment by cosminardeleanu** [comment]
I have the same issue:
```php
class Test
{
    public function __construct()
    {
        $memcached = new \Memcached();
        $memcached->set('key', 'whatever');
    }

    public function wtf()
    {
        $whatever = 'tests';

        function () use ($whatever) {
            return $whatever;
        };
    }
}
(new Test())->wtf();
```

When executing this file from cli, i get
> PHP Notice:  Undefined variable: whatever in /home/vagrant/www/a.php on line 14
Php version : PHP 7.0.6-1+donate.sury.org~trusty+1 (cli) ( NTS )

**Comment by pyrou** [comment]
Another test case :

```<?php

(new Memcached)->set("key", "a");
(new Memcached)->set("key", "c");

$test = create_function('', '$a = 10; return $a;');

var_dump($test()); // NULL

// PHP Notice:  Undefined variable: a in [...]/test.php(6) : runtime-created function on line 1

$test = create_function('', '$b = 10; return $b;');

var_dump($test()); // int(10) // $b is working as expected

$test = create_function('', '$c = 10; return $c;');

var_dump($test()); // NULL

// PHP Notice:  Undefined variable: c in [...]/test.php(16) : runtime-created function on line 1```
