### ISSUE TITLE
Signature change in PHP7 branch getMulti

### ISSUE THREAD

**Issue by EugenMayer** [php-memcached-dev/php-memcached#229]
Seems like the signature changed 

`Warning: Memcached::getMulti() expects at most 2 parameters, 3 given`

code
`$results = $mc->getMulti($full_keys, $null, Memcached::GET_PRESERVE_ORDER);`

Seems like it was allowed and has not been updated here:

https://github.com/php-memcached-dev/php-memcached/blob/php7/memcached-api.php#L196

But not according to the code, it has been removed (cas_tokens)

https://github.com/php-memcached-dev/php-memcached/blob/php7/php_memcached.c#L3732 

Maybe this is related to https://github.com/php-memcached-dev/php-memcached/pull/214#issuecomment-191829027 ?

**Comment by mkoppanen** [comment]
Correct, api.php is not up to date regarding latest changes. PRs are welcome

**Comment by EugenMayer** [comment]
Well beside the api.php, this should also be mentioned in the changelogs - since those are breaking changes. You need to consider this, before making this live - this will need actions on all platforms implementing memcache. Is that all by intention - it seems rather ,it slipped through unnoticed

**Comment by mkoppanen** [comment]
It is mentioned in the changelog in package.xml. It is by intention as it resolves the issues in #126

**Comment by TysonAndre** [comment]
https://github.com/php-memcached-dev/php-memcached/issues/248 seems to be related to this

**Comment by sodabrew** [comment]
This is documented now.
