### ISSUE TITLE
php_memcached.c:4511: error: too many arguments to function ‘zend_register_internal_class_ex’

### ISSUE THREAD

**Issue by indonesaku** [php-memcached-dev/php-memcached#230]

**Comment by indonesaku** [comment]
I use php 7.0.4 

/usr/local/src/php-memcached/php_memcached.c:247: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:247: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:247: warning: passing argument 1 of ‘__builtin_strlen’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:247: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:247: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:247: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:247: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:247: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:247: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:247: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strlen’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strlen’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:249: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:249: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:254: error: ‘new_value_length’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:254: error: (Each undeclared identifier is reported only once
/usr/local/src/php-memcached/php_memcached.c:254: error: for each function it appears in.)
/usr/local/src/php-memcached/php_memcached.c:254: warning: passing argument 6 of ‘OnUpdateString’ makes integer from pointer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_ini.h:162: note: expected ‘int’ but argument is of type ‘void *’
/usr/local/src/php-memcached/php_memcached.c:254: error: too many arguments to function ‘OnUpdateString’
/usr/local/src/php-memcached/php_memcached.c: In function ‘OnUpdateSerializer’:
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strlen’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strlen’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:261: warning: passing argument 1 of ‘__builtin_strcmp’ from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:261: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
/usr/local/src/php-memcached/php_memcached.c:281: error: ‘new_value_length’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:281: warning: passing argument 6 of ‘OnUpdateString’ makes integer from pointer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_ini.h:162: note: expected ‘int’ but argument is of type ‘void *’
/usr/local/src/php-memcached/php_memcached.c:281: error: too many arguments to function ‘OnUpdateString’
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_printable_func’:
/usr/local/src/php-memcached/php_memcached.c:345: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/usr/local/src/php-memcached/php_memcached.c:346: error: ‘zend_fcall_info’ has no member named ‘object_ptr’
/usr/local/src/php-memcached/php_memcached.c:348: error: invalid type argument of ‘unary *’ (have ‘zval’)
/usr/local/src/php-memcached/php_memcached.c:349: error: invalid type argument of ‘unary *’ (have ‘zval’)
/usr/local/src/php-memcached/php_memcached.c:352: error: invalid type argument of ‘unary *’ (have ‘zval’)
/usr/local/src/php-memcached/php_memcached.c:367:62: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memcached_on_new_callback’:
/usr/local/src/php-memcached/php_memcached.c:367: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:374: warning: assignment from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:376: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
/usr/local/src/php-memcached/php_memcached.c:388: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached___construct’:
/usr/local/src/php-memcached/php_memcached.c:426: error: ‘zend_rsrc_list_entry’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:426: error: ‘le’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:432: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:154: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
/usr/local/src/php-memcached/php_memcached.c:432: error: too many arguments to function ‘zend_hash_find’
/usr/local/src/php-memcached/php_memcached.c:506: error: expected ‘;’ before ‘le’
/usr/local/src/php-memcached/php_memcached.c:511:49: error: macro "zend_hash_update" passed 6 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c:510: error: ‘zend_hash_update’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:742:62: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_getMulti_impl’:
/usr/local/src/php-memcached/php_memcached.c:742: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:746: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:746: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:746: warning: passing argument 1 of ‘_convert_to_string’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:243: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:750: warning: assignment makes pointer from integer without a cast
/usr/local/src/php-memcached/php_memcached.c:844: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:944:63: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_getDelayed_impl’:
/usr/local/src/php-memcached/php_memcached.c:944: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:948: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:948: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:948: warning: passing argument 1 of ‘_convert_to_string’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:243: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:952: warning: assignment makes pointer from integer without a cast
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_fetch’:
/usr/local/src/php-memcached/php_memcached.c:1064: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1070: warning: passing argument 4 of ‘add_assoc_stringl_ex’ discards qualifiers from pointer target type
/usr/local/src/php-7.0.4/include/php/Zend/zend_API.h:397: note: expected ‘char *’ but argument is of type ‘const char *’
/usr/local/src/php-memcached/php_memcached.c:1070: error: too many arguments to function ‘add_assoc_stringl_ex’
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_fetchAll’:
/usr/local/src/php-memcached/php_memcached.c:1121: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1129: warning: passing argument 4 of ‘add_assoc_stringl_ex’ discards qualifiers from pointer target type
/usr/local/src/php-7.0.4/include/php/Zend/zend_API.h:397: note: expected ‘char *’ but argument is of type ‘const char *’
/usr/local/src/php-memcached/php_memcached.c:1129: error: too many arguments to function ‘add_assoc_stringl_ex’
/usr/local/src/php-memcached/php_memcached.c:1271:65: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_setMulti_impl’:
/usr/local/src/php-memcached/php_memcached.c:1271: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:1273: warning: passing argument 2 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:168: note: expected ‘struct zend_string **’ but argument is of type ‘char **’
/usr/local/src/php-memcached/php_memcached.c:1273: warning: passing argument 4 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:168: note: expected ‘HashPosition *’ but argument is of type ‘ulong *’
/usr/local/src/php-memcached/php_memcached.c:1273: error: too many arguments to function ‘zend_hash_get_current_key_ex’
/usr/local/src/php-memcached/php_memcached.c:1414:47: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_store_impl’:
/usr/local/src/php-memcached/php_memcached.c:1414: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:1434:47: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c:1764:65: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_deleteMulti_impl’:
/usr/local/src/php-memcached/php_memcached.c:1764: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:1768: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1768: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1768: warning: passing argument 1 of ‘_convert_to_string’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:243: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1776: warning: assignment makes pointer from integer without a cast
/usr/local/src/php-memcached/php_memcached.c:1780: warning: passing argument 4 of ‘memcached_delete_by_key’ makes pointer from integer without a cast
/usr/local/include/libmemcached-1.0/delete.h:50: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1783: warning: passing argument 1 of ‘strlen’ makes pointer from integer without a cast
/usr/include/string.h:397: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1783: warning: passing argument 2 of ‘add_assoc_long_ex’ makes pointer from integer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_API.h:390: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1785: warning: passing argument 1 of ‘strlen’ makes pointer from integer without a cast
/usr/include/string.h:397: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1785: warning: passing argument 2 of ‘add_assoc_bool_ex’ makes pointer from integer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_API.h:392: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1965:67: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_addServers’:
/usr/local/src/php-memcached/php_memcached.c:1965: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:1973: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/php-memcached/php_memcached.c:1976: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/php-memcached/php_memcached.c:1976: warning: passing argument 1 of ‘zend_hash_internal_pointer_reset_ex’ makes pointer from integer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:172: note: expected ‘struct HashTable *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1979:71: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c:1985: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/php-memcached/php_memcached.c:1985: warning: passing argument 1 of ‘zend_hash_move_forward_ex’ makes pointer from integer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:166: note: expected ‘struct HashTable *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1986:68: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c:1991: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1991: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1991: warning: passing argument 1 of ‘_convert_to_string’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:243: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1992: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1992: warning: passing argument 1 of ‘convert_to_long’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:244: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:1997: error: invalid type argument of ‘->’ (have ‘int’)
/usr/local/src/php-memcached/php_memcached.c:1997: warning: passing argument 1 of ‘zend_hash_move_forward_ex’ makes pointer from integer without a cast
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:166: note: expected ‘struct HashTable *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:1998:71: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c:2002: warning: passing argument 1 of ‘zval_get_type’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_types.h:326: note: expected ‘const struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:2002: warning: passing argument 1 of ‘convert_to_long’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_operators.h:244: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:2007: warning: passing argument 2 of ‘memcached_server_list_append_with_weight’ makes pointer from integer without a cast
/usr/local/include/libmemcached-1.0/server_list.h:58: note: expected ‘const char *’ but argument is of type ‘int’
/usr/local/src/php-memcached/php_memcached.c:2079:90: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_getServerByKey’:
/usr/local/src/php-memcached/php_memcached.c:2079: error: ‘add_assoc_string’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2147:60: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_getLastErrorMessage’:
/usr/local/src/php-memcached/php_memcached.c:2147: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2204:90: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_getLastDisconnectedServer’:
/usr/local/src/php-memcached/php_memcached.c:2204: error: ‘add_assoc_string’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_dump_func_callback’:
/usr/local/src/php-memcached/php_memcached.c:2287: error: too many arguments to function ‘add_next_index_string’
/usr/local/src/php-memcached/php_memcached.c:2366:28: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_getOption’:
/usr/local/src/php-memcached/php_memcached.c:2366: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2563:67: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘s_zval_to_uint32_array’:
/usr/local/src/php-memcached/php_memcached.c:2563: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2679:67: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_setOptions’:
/usr/local/src/php-memcached/php_memcached.c:2679: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2682: warning: passing argument 2 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:168: note: expected ‘struct zend_string **’ but argument is of type ‘char **’
/usr/local/src/php-memcached/php_memcached.c:2682: warning: passing argument 4 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:168: note: expected ‘HashPosition *’ but argument is of type ‘ulong *’
/usr/local/src/php-memcached/php_memcached.c:2682: error: too many arguments to function ‘zend_hash_get_current_key_ex’
/usr/local/src/php-memcached/php_memcached.c:2787:38: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: In function ‘zim_Memcached_getResultMessage’:
/usr/local/src/php-memcached/php_memcached.c:2787: error: ‘RETURN_STRING’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2798:35: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
/usr/local/src/php-memcached/php_memcached.c:2798: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2802:86: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
/usr/local/src/php-memcached/php_memcached.c: At top level:
/usr/local/src/php-memcached/php_memcached.c:2872: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘php_memc_new’
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_dtor’:
/usr/local/src/php-memcached/php_memcached.c:2927: error: ‘rsrc’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_sess_dtor’:
/usr/local/src/php-memcached/php_memcached.c:2936: error: ‘rsrc’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2953:76: error: macro "add_assoc_string" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_do_serverlist_callback’:
/usr/local/src/php-memcached/php_memcached.c:2953: error: ‘add_assoc_string’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:2998:119: error: macro "add_assoc_stringl" passed 5 arguments, but takes just 4
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_do_stats_callback’:
/usr/local/src/php-memcached/php_memcached.c:2998: error: ‘add_assoc_stringl’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_do_version_callback’:
/usr/local/src/php-memcached/php_memcached.c:3028: error: too many arguments to function ‘add_assoc_stringl_ex’
/usr/local/src/php-memcached/php_memcached.c: In function ‘s_compress_value’:
/usr/local/src/php-memcached/php_memcached.c:3108: warning: passing argument 2 of ‘compress’ from incompatible pointer type
/usr/include/zlib.h:1095: note: expected ‘uLongf *’ but argument is of type ‘size_t *’
/usr/local/src/php-memcached/php_memcached.c: In function ‘s_serialize_value’:
/usr/local/src/php-memcached/php_memcached.c:3193: warning: passing argument 2 of ‘php_var_serialize’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/ext/standard/php_var.h:56: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3196: error: ‘smart_str’ has no member named ‘c’
/usr/local/src/php-memcached/php_memcached.c:3206: error: ‘smart_str’ has no member named ‘len’
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_zval_to_payload’:
/usr/local/src/php-memcached/php_memcached.c:3243: error: ‘IS_BOOL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:3261: error: ‘smart_str’ has no member named ‘c’
/usr/local/src/php-memcached/php_memcached.c:3262: error: ‘smart_str’ has no member named ‘len’
/usr/local/src/php-memcached/php_memcached.c:3284: error: ‘smart_str’ has no member named ‘len’
/usr/local/src/php-memcached/php_memcached.c: In function ‘s_unserialize_value’:
/usr/local/src/php-memcached/php_memcached.c:3351: warning: passing argument 1 of ‘php_var_unserialize’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/ext/standard/php_var.h:57: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3441:43: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_zval_from_payload’:
/usr/local/src/php-memcached/php_memcached.c:3441: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:3444:43: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_get_exception_base’:
/usr/local/src/php-memcached/php_memcached.c:3539: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_hash.h:154: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
/usr/local/src/php-memcached/php_memcached.c:3539: error: too many arguments to function ‘zend_hash_find’
/usr/local/src/php-memcached/php_memcached.c:3574:37: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_do_cache_callback’:
/usr/local/src/php-memcached/php_memcached.c:3574: error: ‘ZVAL_STRINGL’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:3583: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
/usr/local/src/php-memcached/php_memcached.c:3584: warning: assignment from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:3627: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3630: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3631: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c: In function ‘php_memc_do_result_callback’:
/usr/local/src/php-memcached/php_memcached.c:3655: error: ‘zend_fcall_info’ has no member named ‘retval_ptr_ptr’
/usr/local/src/php-memcached/php_memcached.c:3656: warning: assignment from incompatible pointer type
/usr/local/src/php-memcached/php_memcached.c:3671: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3678: warning: passing argument 4 of ‘add_assoc_stringl_ex’ discards qualifiers from pointer target type
/usr/local/src/php-7.0.4/include/php/Zend/zend_API.h:397: note: expected ‘char *’ but argument is of type ‘const char *’
/usr/local/src/php-memcached/php_memcached.c:3678: error: too many arguments to function ‘add_assoc_stringl_ex’
/usr/local/src/php-memcached/php_memcached.c:3693: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c:3695: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/src/php-7.0.4/include/php/Zend/zend_variables.h:112: note: expected ‘struct zval *’ but argument is of type ‘struct zval **’
/usr/local/src/php-memcached/php_memcached.c: In function ‘zm_startup_memcached’:
/usr/local/src/php-memcached/php_memcached.c:4499: error: ‘php_memc_new’ undeclared (first use in this function)
/usr/local/src/php-memcached/php_memcached.c:4511: error: too many arguments to function ‘zend_register_internal_class_ex’
make: *** [php_memcached.lo] Error 1

**Comment by mkoppanen** [comment]
Use php7 branch

**Comment by hiloy** [comment]
git@github.com:php7-extensions/ext-php7-memcached.git
