### ISSUE TITLE
Problem with building php-memcached with php7 on ubuntu 12.04

### ISSUE THREAD

**Issue by cinek810** [php-memcached-dev/php-memcached#231]
Hi guys, 

Because circle ci provides ubuntu 12.04, I'm trying to build php-memcached extension there. I'm ending with error:
<pre>
/bin/bash /usr/local/php-memcached/libtool --mode=compile cc -I/usr/local/php7/include/php    -I. -I/usr/local/php-memcached -DPHP_ATOM_INC -I/usr/local/php-memcached/include -I/usr/local/php-memcached/main -I/usr/local/php-memcached -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib   -c /usr/local/php-memcached/php_memcached_session.c -o php_memcached_session.lo 
 cc -I/usr/local/php7/include/php -I. -I/usr/local/php-memcached -DPHP_ATOM_INC -I/usr/local/php-memcached/include -I/usr/local/php-memcached/main -I/usr/local/php-memcached -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/php7/include/php -I/usr/local/php7/include/php/main -I/usr/local/php7/include/php/TSRM -I/usr/local/php7/include/php/Zend -I/usr/local/php7/include/php/ext -I/usr/local/php7/include/php/ext/date/lib -c /usr/local/php-memcached/php_memcached_session.c  -fPIC -DPIC -o .libs/php_memcached_session.o
/usr/local/php-memcached/php_memcached_session.c: In function 's_configure_from_ini_values':
/usr/local/php-memcached/php_memcached_session.c:221:22: error: 'MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS' undeclared (first use in this function)
   check_set_behavior(MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS, 1);
                      ^
/usr/local/php-memcached/php_memcached_session.c:195:42: note: in definition of macro 'check_set_behavior'
  if ((rc = memcached_behavior_set(memc, (behavior), (value))) != MEMCACHED_SUCCESS) { \
                                          ^
/usr/local/php-memcached/php_memcached_session.c:221:22: note: each undeclared identifier is reported only once for each function it appears in
   check_set_behavior(MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS, 1);
                      ^
/usr/local/php-memcached/php_memcached_session.c:195:42: note: in definition of macro 'check_set_behavior'
  if ((rc = memcached_behavior_set(memc, (behavior), (value))) != MEMCACHED_SUCCESS) { \
                                          ^
/usr/local/php-memcached/php_memcached_session.c:229:32: error: 'MEMCACHED_CALLBACK_NAMESPACE' undeclared (first use in this function)
   memcached_callback_set(memc, MEMCACHED_CALLBACK_NAMESPACE, MEMC_SESS_STR_INI(prefix));
                                ^
make: *** [php_memcached_session.lo] Error 1
</pre>

Anyone have idea where the problem is?

**Comment by mkoppanen** [comment]
Hey, what version of libmemcached is that?

**Comment by cinek810** [comment]
from package information it looks like:  0.44-1.1build1
