### ISSUE TITLE
Update memcached.ini for php7 branch/pending release to reflect new ini settings and defaults.

### ISSUE THREAD

**Issue by TysonAndre** [php-memcached-dev/php-memcached#233]
The ini entries in the documentation don't reflect the ini settings or code used in php_memcached.c.
Some options were renamed (E.g. sess_binary was renamed to sess_binary_protocol), some options had their defaults changed, and new options were added.

Before an official release is created for php7, this should be changed. Having up to date documentation also helps contributors and testers.

**Comment by sodabrew** [comment]
Thanks for the many doc updates so far! Would you give the php7 branch another once-over to see if any items remain before closing this issue?

**Comment by TysonAndre** [comment]
It seems fine - the binary session serializer was the only issue I had. scanning php_memcached.c and memcached.ini again, they seem consistent.

I'd suggest documenting the change to session protocol setting and defaults in the Changelog when putting together release notes
