### ISSUE TITLE
php7安装有警告，install with php 7,there has one warning 

### ISSUE THREAD

**Issue by lujunjie521** [php-memcached-dev/php-memcached#237]
home/phpredis/cluster_library.c: 在函数‘cluster_multibulk_resp_recursive’中:
/home/phpredis/cluster_library.c:139:17: 警告：传递‘redis_sock_gets’的第 4 个参数时在不兼容的指针类型间转换 [默认启用]
                 if(redis_sock_gets(sock, buf, sizeof(buf), &r->len) < 0) {
                 ^
In file included from /home/phpredis/cluster_library.c:3:0:
/home/phpredis/library.h:18:19: 附注：需要类型‘size_t *’，但实参的类型为‘long long int *’
 PHP_REDIS_API int redis_sock_gets(RedisSock *redis_sock, char *buf, int buf_size, size_t* line_len TSRMLS_DC);
                   ^

**Comment by Timandes** [comment]
哥，你发错地方了吧……
