### ISSUE TITLE
Memleak in getStats() with PHP >= 7.0.3

### ISSUE THREAD

**Issue by GreenRover** [php-memcached-dev/php-memcached#238]
Hello, ich get:

Fatal error: Allowed memory size of 2147483648 bytes exhausted at /srv/php7/php7/Zend/zend_hash.c:140 (tried to allocate 69116610204 bytes

If i call   
```
$m = new Memcached();
$m->addServer(
                    $config['resources']['memcache']['params']['host'],
                    $config['resources']['memcache']['params']['port']
                );
$m->getStats()
```

But only for PHP 7 greater 7.0.2
7.0.2 is the last working.
7.0.5RC1 is still not working.

**Comment by afilippov1985** [comment]
the error may be here

https://github.com/php-memcached-dev/php-memcached/blob/php7/php_memcached.c#L2635

```c
if (!server_values) {
	zval zv;
	array_init(&zv);

	server_values = &zv;
	add_assoc_zval_ex(return_value, server_key, server_key_len, server_values);
}

spprintf (&buffer, 0, "%.*s", value_length, value);

/* Check type */
if (s_long_value (buffer, &long_val)) {
	add_assoc_long(server_values, key, long_val);
}
else if (s_double_value (buffer, &d_val)) {
	add_assoc_double(server_values, key, d_val);
}
else {
	add_assoc_stringl_ex(server_values, key, key_length, value, value_length);
}
```

line 2635: declare `zv`
line 2638: get pointer to `zv` and save it in `server_values`
line 2640: `zv` destroyed
lines 2646, 2649, 2652: use pointer to destroyed variable
