### ISSUE TITLE
increment, decrement, add are not working properly with zero int value in 2.1.0 with binary protocol enabled.

### ISSUE THREAD

**Issue by viktorAndreevichMorozov** [php-memcached-dev/php-memcached#242]
Test script and output in gist
https://gist.github.com/viktorAndreevichMorozov/37aa9ec068bb9a77f1f89c94bd494dc4

**Comment by sodabrew** [comment]
I'm not able to reproduce this with php-memcached 3.0.0 and PHP 7.
