### ISSUE TITLE
php_memcached_private.h:44:40: fatal error:     ext/standard/php_smart_str.h: No such file or directory

### ISSUE THREAD

**Issue by emiglobetrotting** [php-memcached-dev/php-memcached#251]
cd php-memcached
    /etc/php7/bin/phpize
    ./configure --prefix='/etc/php7' --with-libmemcached-dir='/usr' --disable-memcached-sasl  --with- libdir='/lib/x86_64-linux-gnu' --with-php-config='/etc/php7/bin/php-config'
    make && make install

./configure run successfully, but when i try to make && make install i'm having the error below:

    In file included from /php-src/ext/php-memcached/php_memcached.c:26:0:
    /php-src/ext/php-memcached/php_memcached_private.h:44:40: fatal error:     ext/standard/php_smart_str.h: No such file or directory
     #include <ext/standard/php_smart_str.h>
                                        ^
    compilation terminated.
    make: *** [php_memcached.lo] Error 1

**Comment by emiglobetrotting** [comment]
It seems i'm using non php7 version of php-memcached, so i removed the old one and did
    
    cd php-src/ext
    git clone https://github.com/php-memcached-dev/php-memcached -b php7 php-memcached
    cd php-memcached
    /etc/php7/bin/phpize
    ./configure --prefix='/etc/php7' --with-libmemcached-dir='/usr' --disable-memcached-sasl  --with-libdir='/lib/x86_64-linux-gnu' --with-php-config='/etc/php7/bin/php-config'
    make && make install
    make test

The test result is here below, is it okay to accept this result
    
    Number of tests :  126               112
    Tests skipped   :   14 ( 11.1%) --------
    Tests warned    :    0 (  0.0%) (  0.0%)
    Tests failed    :   20 ( 15.9%) ( 17.9%)
    Expected fail   :    1 (  0.8%) (  0.9%)
    Tests passed    :   91 ( 72.2%) ( 81.2%)

**Comment by Timandes** [comment]
You can enter the directories with failed cases.
Log files will tell you what was going on that moment.

**Comment by emiglobetrotting** [comment]
okay, thanks.
