### ISSUE TITLE
have some error when compile with php7

### ISSUE THREAD

**Issue by mengjie1977** [php-memcached-dev/php-memcached#257]
/home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.c:2651:56: warning: passing argument 4 of 'add_assoc_stringl_ex' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   add_assoc_stringl_ex(server_values, key, key_length, value, value_length);
                                                        ^~~~~
In file included from /usr/local/php-shenma/include/php/main/php.h:39:0,
                 from /home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.h:22,
                 from /home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.c:25:
/usr/local/php-shenma/include/php/Zend/zend_API.h:397:14: note: expected 'char *' but argument is of type 'const char *'
 ZEND_API int add_assoc_stringl_ex(zval *arg, const char *key, size_t key_len, char *str, size_t length);
              ^~~~~~~~~~~~~~~~~~~~
/home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.c: In function 's_server_cursor_list_servers_cb':
/home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.c:3369:35: warning: passing argument 4 of 'add_assoc_string_ex' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  add_assoc_string(&array, "host", memcached_server_name(instance));
                                   ^
/usr/local/php-shenma/include/php/Zend/zend_API.h:406:96: note: in definition of macro 'add_assoc_string'
 #define add_assoc_string(__arg, __key, __str) add_assoc_string_ex(__arg, __key, strlen(__key), __str)
                                                                                                ^~~~~
/usr/local/php-shenma/include/php/Zend/zend_API.h:396:14: note: expected 'char *' but argument is of type 'const char *'
 ZEND_API int add_assoc_string_ex(zval *arg, const char *key, size_t key_len, char *str);
              ^~~~~~~~~~~~~~~~~~~
/home/jie.meng/rpmbuild/BUILD/php-memcached-php7/php_memcached.c:3371:35: warning: passing argument 4 of 'add_assoc_string_ex' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  add_assoc_string(&array, "type", memcached_server_type(instance));

**Comment by laruence** [comment]
I don't see any errors, just some warnings?  anyway, they should be all fixed.
