### ISSUE TITLE
session_start(): Failed to create session ID with php 7

### ISSUE THREAD

**Issue by zhuleilei** [php-memcached-dev/php-memcached#259]
it happens where the backend is a twemproxy server,It's ok when the backend is a memcached server.

**Comment by zhuleilei** [comment]
I use tcpdump to capture the stream.and found it's difference between the php7 and php5.

[php5 twemproxy.zip](https://github.com/php-memcached-dev/php-memcached/files/340828/php5.twemproxy.zip)
[php7 twemproxy.zip](https://github.com/php-memcached-dev/php-memcached/files/340829/php7.twemproxy.zip)

**Comment by zhuleilei** [comment]
got it
the setting memcached.sess_binary_protocol is 1 on php 7 but it's 0 on php 5.
and twemproxy only supports the ascii protocol.

**Comment by LucasBG0** [comment]
> got it
> the setting memcached.sess_binary_protocol is 1 on php 7 but it's 0 on php 5.
> and twemproxy only supports the ascii protocol.

I was having the same problem with Mcrouter, changing memcached.sess_binary_protocol to off worked. Thanks
