### ISSUE TITLE
How enable gzip-compression? (nginx return corrupted data from memcached)

### ISSUE THREAD

**Issue by Driver86** [php-memcached-dev/php-memcached#278]
nginx return corrupted data from memcached: http://stackoverflow.com/questions/11503111/nginx-return-corrupted-data-from-memcached/20171995

http://stackoverflow.com/a/20171995 - how enable gzip-compression?

**Comment by sodabrew** [comment]
gzip is not supported. The options are fastlz and zlib: https://github.com/php-memcached-dev/php-memcached/blob/master/memcached.ini#L75
