### ISSUE TITLE
configure option enable-memcached-igbinary not working?

### ISSUE THREAD

**Issue by kn007** [php-memcached-dev/php-memcached#283]
Now igbinary for php7 published.

When I configure memcached module with `enable-memcached-igbinary`, it's return
```
checking for memcached igbinary support... enabled
```
But after make install, php return memcached status:
```
igbinary support	no
```

Memcached::SERIALIZER_IGBINARY return `false`
Memcached::HAVE_IGBINARY also return `false`

**Comment by sodabrew** [comment]
It works for me? I would need to know more about what you've tried to understand the problem.

**Comment by kn007** [comment]
I'm sorry that I forget close issue, also forget how to solve........
It's work fine now.
