### ISSUE TITLE
can't not work in php7

### ISSUE THREAD

**Issue by JamesKid** [php-memcached-dev/php-memcached#285]
when i restart my php-fpm it says '
/usr/local/php7/lib/php/extensions/no-debug-non-zts-20151012/memcached.so doesn't appear to be a valid Zend extension'

**Comment by laruence** [comment]
you probably use:
```
zend_extension=memcached.so
```

and you should use:
```
extension=memcached.so
```

**Comment by JamesKid** [comment]
all right ,thank you

**Comment by visoeclipse** [comment]
extension = "memcached.so"
//usr/local/php-7.1.9/lib/php/extensions/debug-non-zts-20160303/memcached.so doesn't appear to be a valid Zend extension

在debug下似乎有问题

**Comment by visoeclipse** [comment]
@laruence 
extension = "memcached.so"
//usr/local/php-7.1.9/lib/php/extensions/debug-non-zts-20160303/memcached.so doesn't appear to be a valid Zend extension

在debug下似乎有问题

**Comment by visoeclipse** [comment]
@laruence 
似乎开启debug，没办法加载memcached.so（该文件存在且配置了ini）
