### ISSUE TITLE
error, branch php7 configure on CentOS release 6.8 (Final) x86_64 with php7.1.0 and libmemcached-0.31-1.1.el6.x86_64

### ISSUE THREAD

**Issue by busyfree** [php-memcached-dev/php-memcached#286]
configure parameter : ./configure --with-php-config=/usr/local/servers/php-7.1.0/bin/php-config  --disable-memcached-sasl
[root:php-memcached-php7]#make
/bin/sh /home/share/disk1/resource/php-memcached-php7/libtool --mode=compile cc -I/usr/local/servers/php-7.1.0/include/php    -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib   -c /home/share/disk1/resource/php-memcached-php7/php_memcached.c -o php_memcached.lo 
/bin/sh /home/share/disk1/resource/php-memcached-php7/libtool --mode=compile cc -I/usr/local/servers/php-7.1.0/include/php    -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib   -c /home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.c -o php_libmemcached_compat.lo 
/bin/sh /home/share/disk1/resource/php-memcached-php7/libtool --mode=compile cc -I/usr/local/servers/php-7.1.0/include/php    -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib   -c /home/share/disk1/resource/php-memcached-php7/g_fmt.c -o g_fmt.lo 
/bin/sh /home/share/disk1/resource/php-memcached-php7/libtool --mode=compile cc -I/usr/local/servers/php-7.1.0/include/php    -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib   -c /home/share/disk1/resource/php-memcached-php7/fastlz/fastlz.c -o fastlz/fastlz.lo 
mkdir .libs
mkdir .libs
mkdir .libs
mkdir: cannot create directory `.libs': File exists
mkdir: cannot create directory `.libs': File exists
 cc -I/usr/local/servers/php-7.1.0/include/php -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -c /home/share/disk1/resource/php-memcached-php7/g_fmt.c  -fPIC -DPIC -o .libs/g_fmt.o
 cc -I/usr/local/servers/php-7.1.0/include/php -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -c /home/share/disk1/resource/php-memcached-php7/php_memcached.c  -fPIC -DPIC -o .libs/php_memcached.o
 cc -I/usr/local/servers/php-7.1.0/include/php -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -c /home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.c  -fPIC -DPIC -o .libs/php_libmemcached_compat.o
mkdir fastlz/.libs
 cc -I/usr/local/servers/php-7.1.0/include/php -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -c /home/share/disk1/resource/php-memcached-php7/fastlz/fastlz.c  -fPIC -DPIC -o fastlz/.libs/fastlz.o
In file included from /home/share/disk1/resource/php-memcached-php7/php_memcached_private.h:28,
                 from /home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.c:18:
/home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.h:56: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘php_memcached_instance_st’
/bin/sh /home/share/disk1/resource/php-memcached-php7/libtool --mode=compile cc -I/usr/local/servers/php-7.1.0/include/php    -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib   -c /home/share/disk1/resource/php-memcached-php7/php_memcached_session.c -o php_memcached_session.lo 
In file included from /home/share/disk1/resource/php-memcached-php7/php_memcached_private.h:28,
                 from /home/share/disk1/resource/php-memcached-php7/php_memcached.c:25:
/home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.h:56: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘php_memcached_instance_st’
make: *** [php_libmemcached_compat.lo] Error 1
make: *** Waiting for unfinished jobs....
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:404: error: expected declaration specifiers or ‘...’ before ‘php_memcached_instance_st’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:407: error: expected declaration specifiers or ‘...’ before ‘php_memcached_instance_st’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘php_memc_mget_apply’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:684: warning: passing argument 4 of ‘memcached_mget_by_key’ from incompatible pointer type
/usr/include/libmemcached/memcached_get.h:38: note: expected ‘char **’ but argument is of type ‘const char **’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:686: warning: passing argument 2 of ‘memcached_mget’ from incompatible pointer type
/usr/include/libmemcached/memcached_get.h:25: note: expected ‘char **’ but argument is of type ‘const char **’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached___construct’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:1206: warning: assignment makes pointer from integer without a cast
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:1209: warning: assignment makes pointer from integer without a cast
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getServerList’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2430: warning: assignment from incompatible pointer type
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getServerByKey’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2441: error: ‘php_memcached_instance_st’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2441: error: (Each undeclared identifier is reported only once
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2441: error: for each function it appears in.)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2441: error: expected ‘;’ before ‘server_instance’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2452: error: ‘server_instance’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2459:87: error: macro "memcached_server_name" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2459: error: ‘memcached_server_name’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2460:77: error: macro "memcached_server_port" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2460: error: ‘memcached_server_port’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getLastDisconnectedServer’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2569: error: ‘php_memcached_instance_st’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2569: error: expected ‘;’ before ‘server_instance’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2578: error: ‘server_instance’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2584:87: error: macro "memcached_server_name" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2584: error: ‘memcached_server_name’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2585:77: error: macro "memcached_server_port" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2585: error: ‘memcached_server_port’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: At top level:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2620: error: expected ‘)’ before ‘instance’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2630:68: error: macro "memcached_server_name" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2630:101: error: macro "memcached_server_port" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getStats’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2672: error: ‘s_stat_execute_cb’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getVersion’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2699: warning: assignment from incompatible pointer type
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘zim_Memcached_getAllKeys’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2731: warning: assignment from incompatible pointer type
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘php_memc_set_option’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2857: error: ‘MEMCACHED_INVALID_ARGUMENTS’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:2987: error: ‘MEMCACHED_BEHAVIOR_MAX’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: At top level:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3351: error: expected declaration specifiers or ‘...’ before ‘php_memcached_instance_st’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3357:73: error: macro "memcached_server_name" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘s_server_cursor_list_servers_cb’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3357: error: ‘memcached_server_name’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3358:66: error: macro "memcached_server_port" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3358: error: ‘memcached_server_port’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3359: error: ‘instance’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: At top level:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3370: error: expected declaration specifiers or ‘...’ before ‘php_memcached_instance_st’
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘s_server_cursor_version_cb’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3382: error: ‘instance’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3387:65: error: macro "memcached_server_name" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3387: error: ‘memcached_server_name’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3387:98: error: macro "memcached_server_port" requires 2 arguments, but only 1 given
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:3387: error: ‘memcached_server_port’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c: In function ‘php_memc_register_constants’:
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:4166: error: ‘LIBMEMCACHED_VERSION_HEX’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:4237: error: ‘MEMCACHED_BEHAVIOR_TCP_KEEPALIVE’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:4306: error: ‘MEMCACHED_E2BIG’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:4307: error: ‘MEMCACHED_KEY_TOO_BIG’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached.c:4308: error: ‘MEMCACHED_SERVER_TEMPORARILY_DISABLED’ undeclared (first use in this function)
make: *** [php_memcached.lo] Error 1
 cc -I/usr/local/servers/php-7.1.0/include/php -I. -I/home/share/disk1/resource/php-memcached-php7 -DPHP_ATOM_INC -I/home/share/disk1/resource/php-memcached-php7/include -I/home/share/disk1/resource/php-memcached-php7/main -I/home/share/disk1/resource/php-memcached-php7 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -I/usr/local/servers/php-7.1.0/include/php -I/usr/local/servers/php-7.1.0/include/php/main -I/usr/local/servers/php-7.1.0/include/php/TSRM -I/usr/local/servers/php-7.1.0/include/php/Zend -I/usr/local/servers/php-7.1.0/include/php/ext -I/usr/local/servers/php-7.1.0/include/php/ext/date/lib -c /home/share/disk1/resource/php-memcached-php7/php_memcached_session.c  -fPIC -DPIC -o .libs/php_memcached_session.o
In file included from /home/share/disk1/resource/php-memcached-php7/php_memcached_private.h:28,
                 from /home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:18:
/home/share/disk1/resource/php-memcached-php7/php_libmemcached_compat.h:56: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘php_memcached_instance_st’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘s_configure_from_ini_values’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:217: error: ‘MEMCACHED_BEHAVIOR_RANDOMIZE_REPLICA_READ’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:217: error: (Each undeclared identifier is reported only once
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:217: error: for each function it appears in.)
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:221: error: ‘MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:229: error: ‘MEMCACHED_CALLBACK_NAMESPACE’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘s_pemalloc_fn’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:257: warning: passing argument 1 of ‘memcached_get_user_data’ discards qualifiers from pointer target type
/usr/include/libmemcached/memcached.h:284: note: expected ‘struct memcached_st *’ but argument is of type ‘const struct memcached_st *’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘s_pefree_fn’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:266: warning: passing argument 1 of ‘memcached_get_user_data’ discards qualifiers from pointer target type
/usr/include/libmemcached/memcached.h:284: note: expected ‘struct memcached_st *’ but argument is of type ‘const struct memcached_st *’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘s_perealloc_fn’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:275: warning: passing argument 1 of ‘memcached_get_user_data’ discards qualifiers from pointer target type
/usr/include/libmemcached/memcached.h:284: note: expected ‘struct memcached_st *’ but argument is of type ‘const struct memcached_st *’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘s_pecalloc_fn’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:284: warning: passing argument 1 of ‘memcached_get_user_data’ discards qualifiers from pointer target type
/usr/include/libmemcached/memcached.h:284: note: expected ‘struct memcached_st *’ but argument is of type ‘const struct memcached_st *’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: At top level:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:292: error: expected ‘;’, ‘,’ or ‘)’ before ‘servers’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c: In function ‘ps_open_memcached’:
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:326: error: ‘memcached_server_list_st’ undeclared (first use in this function)
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:326: error: expected ‘;’ before ‘servers’
/home/share/disk1/resource/php-memcached-php7/php_memcached_session.c:329: error: ‘servers’ undeclared (first use in this function)
make: *** [php_memcached_session.lo] Error 1

**Comment by sodabrew** [comment]
libmemcached-0.31 is much too old, you'll need at least 1.0 or higher, with 1.0.16 or higher strongly recommended.

**Comment by busyfree** [comment]
thanks
