### ISSUE TITLE
Can't Install?

### ISSUE THREAD

**Issue by ichadi** [php-memcached-dev/php-memcached#287]
More issues related to installing memcache on Centos 7 / PHP 7.

```
[root@server php-memcached-php7]# phpize   
-bash: phpize: command not found

[root@server php-memcached-php7]# yum install php-devel
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 69.72.212.10
 * base: mirror.math.princeton.edu
 * extras: mirrors.centos.webair.com
 * updates: mirror.cs.pitt.edu
No package php-devel available.
Error: Nothing to do

[root@server php-memcached-php7]# which phpize
/usr/bin/which: no phpize in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin)
```

**Comment by sodabrew** [comment]
You may need the php-devel package in order to compile php extensions. I am not deeply familiar with Centos, so I can only recommend that you search how to do this.

**Comment by karljohns0n** [comment]
Not finding phpize on your system has nothing to do with php-memcached. I see EA4 in your yum repos so I assume you are using EasyApache4 from cPanel. Look in /opt/cpanel/ea-php?/root/usr/bin/phpize, it should be there.
