### ISSUE TITLE
Install at macOS with PHP 7.1

### ISSUE THREAD

**Issue by RafaelPlantard** [php-memcached-dev/php-memcached#288]
How can I install?

**Comment by sodabrew** [comment]
Use the php7 branch

**Comment by RafaelPlantard** [comment]
Thanks I will try.

**Comment by jurgenweber** [comment]
can the php7 branch please be merged and released? What is the hold up?

**Comment by sodabrew** [comment]
The php7 branch is merged as of yesterday, I've been working on the release notes.

**Comment by jurgenweber** [comment]
haha, sorry about that. Missed that captain obvious. How long until it is in pecl, etc?

**Comment by sodabrew** [comment]
The 3.0.0 release will be released Real Soon Now. I'm cleaning up the tickets in preparation.

**Comment by RafaelPlantard** [comment]
That's great @sodabrew!!!

**Comment by jurgenweber** [comment]
an ETA?
