### ISSUE TITLE
Is php-memcached 3.0.0 affected by php bug #73539?

### ISSUE THREAD

**Issue by ralfbecker** [php-memcached-dev/php-memcached#307]
There's a bug in PHP 5.6.28+ and 7.0.13 which causes all session handlers specifying more then one server to give a PHP Fatal error when trying to allocate 4GB of memory: 

- https://bugs.php.net/bug.php?id=73539
- https://bugs.php.net/bug.php?id=73497

I personally only run into it with 5.6.28 and php-memcache (no d!), but there are reports that the issue also affects php-memcached and redis.

Has anyone checked php-memcached 3.0.0 against that issue aka. it working with two memcached servers specified?

**Comment by sodabrew** [comment]
Would you be amenable to testing this and reporting back to the community your findings?

**Comment by ralfbecker** [comment]
Good :)
