### ISSUE TITLE
Failed to write, and not due to blocking: Broken pipe (PHP issue 65123)

### ISSUE THREAD

**Issue by daberlin** [php-memcached-dev/php-memcached#308]
I'm using PHP 7.1.1 with the memcached 1.4.34, igbinary and the latest php_memcached (master from 26.01.2016) and receive a lot of these errors:
Failed to write, and not due to blocking: Broken pipe

The error is exactly as described here:
https://bugs.php.net/bug.php?id=65123

It happens both with tcp and socket connections...
When I switch off binary protocol for both sessions and default, the error disappears.

**Comment by sodabrew** [comment]
This is a known problem with getStats and newer versions of memcached #203
