### ISSUE TITLE
Pecl release for 3.0.x missing

### ISSUE THREAD

**Issue by ralfbecker** [php-memcached-dev/php-memcached#317]
Can we please have a PECL release for v 3.0.x.
Best would be if it got created when ever a new version is released here on Github.

Thanks :)

Ralf

**Comment by carlwgeorge** [comment]
It looks like this has been taken care of now.

* https://pecl.php.net/package/memcached/3.0.0
* https://pecl.php.net/package/memcached/3.0.1
