### ISSUE TITLE
get() returns empty string when connection refused to memcached.

### ISSUE THREAD

**Issue by bdrewery** [php-memcached-dev/php-memcached#32]
PHP 5.3.3

My code looks similar to this:

<pre>
class MemoryCache extends Memcached {
  public function get($key, $callback = null, &$cas_token = null) {
    $results = parent::get($key, $callback, $cas_token);
    if ($results === false) {
      error_log("Cache miss on {$key}");
    }
    return $results;
  }
}

$results = $MemoryCache->get("Key");
if ($results === false) {
  $results = get_the_real_data();
}
do_stuff($results);
</pre>

According to the [documentation](http://us3.php.net/manual/en/memcached.get.php), either the result or _FALSE_ should be returned. However, if the memcached server is down, or connection otherwise refused, `$results` comes out as a blank string `""` (according to `var_dump`). This causes the calling code to get `""` and _do stuff with it_ instead of looking up the real data, due to the `===`.

7deb03e79b8 perhaps related?

I've worked around this by checking `getResultCode()` and acting accordingly if not _Memcached::RES_SUCCESS_ or _Memcached::RES_NOTFOUND_

This also seems to be reported [here](http://us3.php.net/manual/en/memcached.get.php#101904), although as a _NULL_ return value.

Apologies if this is already fixed, or bogus. If it's bogus, the documentation should get updated on php.net :)

**Comment by sodabrew** [comment]
In current revisions of php-memcached, `get` returns false when the server is not connected.
