### ISSUE TITLE
minimum libevent version

### ISSUE THREAD

**Issue by carlwgeorge** [php-memcached-dev/php-memcached#323]
Is there a minimum recommended/required version of libevent needed to build and run this extension?  I noticed that the [Fedora spec file](https://src.fedoraproject.org/cgit/rpms/php-pecl-memcached.git/tree/php-pecl-memcached.spec?id=7d3de6aace6c7a036ad32219d5a01654db67617c#n36) has `BuildRequires: libevent-devel  > 2`, however there is no explanation why in the changelog, and I can't find any reference to a minimum version in the module's source code.

The context of this question is the versions of libevent available in RHEL.
* EL6: 1.4.13
* EL7: 2.0.21

**Comment by sodabrew** [comment]
php-memcached 3.x depends on libmemcached >= 1.0.2 which depends on either libevent >= 1.x or >= 2.x: https://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.0/view/head:/m4/ax_libevent.m4

php-memcached 2.x depends on libmemcached >= 0.44, including >= 1.0.x, which depends on libevent >= 1.x or 2.x. It's highly likely the libmemcached 0.x versions did not support libevent 2.x, but I don't know the cut-off points off the top of my head.

**Comment by carlwgeorge** [comment]
Ah, so it isn't really necessary to put that in the pecl module's spec file, since it gets pulled in recursively by libmemcached.  That works for me.

I also just realized that EL6 ships a libevent2 package.  I may use that if I decide to create a parallel libmemcached package for EL6.

Thanks for the excellent and prompt feedback!
