### ISSUE TITLE
[pecl] There are both 3.0.1 and 3.0.0 on pecl. Which is the latest?

### ISSUE THREAD

**Issue by tmatsuo** [php-memcached-dev/php-memcached#324]
The link for the latest version points to 3.0.0. Which should we use?

**Comment by TysonAndre** [comment]
3.0.1 is newer, I assume the maintainers somehow uploaded them in the other order.

https://github.com/php-memcached-dev/php-memcached/releases

**Comment by sodabrew** [comment]
Use 3.0.1.

Pecl took the creation time stamp instead of the package date to sort, so yes when I back-filled the 3.0.0 package it sorted to the top.

**Comment by sodabrew** [comment]
Update: 3.0.2 is now posted, and is sorted correctly.
