### ISSUE TITLE
PHP 7: Segfault with Igbinary and Variable References

### ISSUE THREAD

**Issue by ssigwart** [php-memcached-dev/php-memcached#326]
Running the following code produces a segmentation fault:
```php
ini_set('memcached.serializer', 'igbinary');
$memcached = new Memcached();
$memcached->addServer('127.0.0.1', 11211);
$a = 'a';
$b = ['a'=>&$a];
$memcached->setMulti($b, 60);
```

Here are the version numbers:
PHP: 7.0.15
igbinary: 2.0.1
memcached: 3.0.0
libmemcached: 1.0.18

The segmentation fault does not occur if you remove the reference (i.e. use `$b = ['a'=>$a];`) or add `ini_set('memcached.serializer', 'php');`

**Comment by sodabrew** [comment]
Thanks for the bug report!

**Comment by sodabrew** [comment]
@TysonAndre does php-memcached require any code changes to benefit from the bug fix in igbinary? Or just note it for users to upgrade their igbinary versions?

**Comment by TysonAndre** [comment]
No, php-memcached doesn't require any code changes.
