### ISSUE TITLE
Install via pecl fails with '.. --with-libmemcached-dir=y' failed

### ISSUE THREAD

**Issue by andrerom** [php-memcached-dev/php-memcached#334]
This is when extending "official" php docker container, where for instance`libmemcached-dev` is [added](https://github.com/ezsystems/docker-php/compare/695e11f...memcached_msgpack#diff-04ec72bcbf7c2ab7c3d17ba1c7b0fa03): 
```
checking for libmemcached location... configure: error: Unable to find memcached.h under y
ERROR: `/tmp/pear/temp/memcached/configure --with-php-config=/usr/local/bin/php-config --with-libmemcached-dir=y' failed
```

Unsure what it is connected to, but as I'm installing via pecl I won't be able to set compile time options so this is all a bit strange.

[Full raw log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/209306686/log.txt) of the build.

**Comment by sodabrew** [comment]
The build is doing executing `yes | pecl install memcached`, which pipes an endless stream of `y` characters into the pecl's stdin. This is because pecl is interactively asking for the path to libmemcached, or the word "no" to indicate that it should find libmemcached on its own.

A solution would be to either `echo no | pecl install memcached` or `echo $(pkg-config libmemcached --variable=prefix) | pecl install memcached` as the command.

**Comment by andrerom** [comment]
Thanks

**Comment by andrerom** [comment]
Is there anyway to get msgpack to be detected when installing from pecl?

**Comment by sodabrew** [comment]
You have to install the msgpack extension first, it should be automatic.

**Comment by andrerom** [comment]
ok, I'll check why it was not picked up. 👍

**Comment by andrerom** [comment]
Hmm, still getting:
```
checking whether to enable memcached msgpack serializer support... no
checking for memcached msgpack support... disabled
```

Despite `msgpack` can be verified via `php -m`.

Code:
```
    && pecl install msgpack \
    && docker-php-ext-enable msgpack \
    \
    && echo no | pecl install memcached \
    && docker-php-ext-enable memcached \
```

[Full log](https://api.travis-ci.org/jobs/209382680/log.txt?deansi=true), also previously attempted to install with `libmsgpack-dev`, but seems like php-msgpack does not need it _(doc also does not have any mention of it)_.
