### ISSUE TITLE
AES encryption support

### ISSUE THREAD

**Issue by Vincent--** [php-memcached-dev/php-memcached#345]
Since libmemcached [v1.0.6](https://twitter.com/brianaker/status/190107828831272960), support for transparent AES encryption is available

As [ suhosin](https://github.com/sektioneins/suhosin7) doesnt seem to be maintained anymore and there no real alternative for php7, is it doable to add AES encryption for session in php-memcached? Happy to work on it if people are interested but I'm not PHP/C expert 😬

**Comment by sodabrew** [comment]
It's just a matter of exposing the `memcached_set_encoding_key()` function into PHP. Pull Requests certainly welcomed! http://docs.libmemcached.org/libmemcached-1.0/memcached_set_encoding_key.html
