### ISSUE TITLE
Add an option to prefer unserializing JSON as arrays over stdClass for old data?

### ISSUE THREAD

**Issue by TysonAndre** [php-memcached-dev/php-memcached#347]
This behavior affects people migrating from json to another serializer and reusing the same key names.

Proposed behavior, in order of precedence:

1. If the current serializer is SERIALIZER_JSON, unserialize as stdClass (unchanged)
2. If the current unserializer is SERIALIZER_JSON_ARRAY, unserialize as array (unchanged)
3. If the new preference for json unserialization is set on that Memcached instance (e.g. `setFallbackJsonUnserializerPreference(bool $qs_array)`, use that to choose array/stdClass
4. Otherwise, if the serializer is something else, unserialize as stdClass (unchanged)

Related lines of php_memcached.c

```c
3454         case MEMC_VAL_IS_JSON:
3455 #ifdef HAVE_JSON_API
3456         {
3457             php_memc_user_data_t *memc_user_data = memcached_get_user_data(memc);
3458             php_json_decode(return_value, ZSTR_VAL(payload), ZSTR_LEN(payload), (memc_user_data->serializer == SERIALIZER_JSON_ARRAY), PHP_JSON_PARSER_DEFAULT_DEPTH);
3459         }
3460 #else
3461             ZVAL_FALSE(return_value);
3462             php_error_docref(NULL, E_WARNING, "could not unserialize value, no json support");
```

It's possible to work around this by temporarily setting the serializer to SERIALIZER_JSON_ARRAY, calling get(), then restoring, but that is inconvenient.

**Comment by sodabrew** [comment]
Is the issue that the fallback changed between php-memcached 2.x and 3.x and you want the ability to select the old behavior?

**Comment by TysonAndre** [comment]
The issue was that I was migrating from JSON arrays to another serializer, I finished already. Its not related to a version change

**Comment by TysonAndre** [comment]
I no longer need this
