### ISSUE TITLE
getStats issue with OPT_BINARY_PROTOCOL and OPT_NO_BLOCK

### ISSUE THREAD

**Issue by ssigwart** [php-memcached-dev/php-memcached#348]
The following code hangs and causes high CPU usage.
```php
$memcached = new Memcached();
$memcached->setOption(Memcached::OPT_NO_BLOCK, true);
$memcached->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$memcached->addServer('127.0.0.1', 11211, 100);
print_r($memcached->getStats());
```

I'm using:
PHP: 5.6.29
memcached: 2.2.0
libmemcached: 1.0.18

**Comment by sodabrew** [comment]
Confirmed this still fails with php-memcached 3.0.3 and PHP 7.1. The `OPT_NO_BLOCK` setting is what triggers the problem. Thanks for reporting this!

**Comment by mtibben** [comment]
Just ran into this using Symfony 3.3 Cache Component which sets `OPT_NO_BLOCK` by default
