### ISSUE TITLE
memcached_increment_with_initial implement wrong

### ISSUE THREAD

**Issue by sidny** [php-memcached-dev/php-memcached#356]
$mc = new Memcached();
$result = $mc->increament('testkey', 1, 0 , 60);
//$result == false
//expect  $result == 1

when the key ‘testkey’ is not exsit  and params has  ‘ initial’，it's always return false；

at php_memcached.c line 2188 ，
“
MEMC_CHECK_KEY(intern, key);
”
the checkpoint should be placed after  line 2195 
“
	if ((!by_key && n_args < 3) || (by_key && n_args < 4)) {
”

**Comment by sodabrew** [comment]
Thank you for the report. Do you have time to prepare a PR that makes the code change and includes a corresponding unit test to demonstrate the correct behavior?

**Comment by sidny** [comment]
branch REL2_0   is right 
branch master is wrong ,
but i'm working with php5.6.x

**Comment by sodabrew** [comment]
I cannot reproduce this on the 3.0 branch:

```
$ cat incr.php
<?php
$mc = new Memcached;
$mc->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$mc->addServer('localhost', 11211);
$result = $mc->increment('testkey', 1, 0, 60);
print_r( var_dump ( $result ) );
?>

$ php -d extension=memcached.so incr.php
int(0)

$ php -d extension=memcached.so incr.php
int(1)
```
