### ISSUE TITLE
compile error on Ubuntu 12.04.5 LTS: php_memcached_session.c:221:3: error: 'MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS' undeclared (first use in this function)

### ISSUE THREAD

**Issue by sebschlue** [php-memcached-dev/php-memcached#362]
I am trying to compile php-memcached extension inside docker ("ubuntu:12.04").

First, I have manually built PHP7 from php-7.0.21.tar.gz source package, which is now installed at /usr/local/php70

Then, I am trying to compile php-memcached extension, which fails with error:

php_memcached_session.c:221:3: error: 'MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS' undeclared (first use in this function)

Here are the details of phpize, configure and make: https://pastebin.com/xGpv1Z1q

Can you please help me getting this compilation error resolved?

**Comment by sodabrew** [comment]
Dup of #231 - the version of libmemcached included is 0.44, which is too old for the PHP 7 version of the extension (requires libmemcached 1.x.
