### ISSUE TITLE
Suggestion about license

### ISSUE THREAD

**Issue by ackintosh** [php-memcached-dev/php-memcached#363]
### Context

`apt-cache search` displays `php-memcached - memcached extension module for PHP5` as shown below.

```
$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
…
…
$ php -i | grep libmemcached
libmemcached version => 1.0.18
$ apt-cache search php | grep memcached
php-memcached - memcached extension module for PHP5, uses libmemcached
```

On the other hand, `php-fpm` is as follows.

```
$ apt-cache search php | grep fpm
php-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary) (default)
php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
```

> php7.0-fpm

So I sent an RFP to register `php 7.0-memcached` in the package repository.

ITP: php7.0-memcached -- memcached extension module for PHP7.x - Debian Bug report logs
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870908

### Suggestion

The PHP license is avoided because of the restrictions it has 😢 .

[Debian position on software licensed under the PHP License](https://ftp-master.debian.org/php-license.html)

If you do not mind, how about changing to GPL or a license compatible with it?
For your convenience, php-fpm is BSD 2-clause 👀 .

https://github.com/dreamcat4/php-fpm/blob/master/LICENSE

Thank you.

**Comment by sodabrew** [comment]
Thank you very much for your packaging efforts!

I don't see the problem about the license, though - according to the linked Debian policy page:

> The PHP license must only be used for PHP and PHP add-ons.

Since this is a PHP extension ("add-on") after all.
