### ISSUE TITLE
Incorect valure returned

### ISSUE THREAD

**Issue by morphles** [php-memcached-dev/php-memcached#366]
Might be hard to believe me, but I'm like 99.999% certain that sometimes php-memcached returns incorrect value from get. Trouble is I have no way to reliably reproduce this, but I have spent hunting the problem on our servers like 4 days, and only sensible conclusion is that sometimes incorrect value is returned. (since php 7.1, php memcached 3.0.3, libmemcached version 1.0.18, previously we were on php 5.6 and did not have such problem).

Some background:
for invalidating cache in large chunks (say all cache entries related to one db table) we have "namespace implementation", certain keys "namespace keys" store numbers, when application needs to get cached value for certain key and a given namespace, we first retrieve value for "namespace key", which is a number, then concatenates "namespace key"~"namespace value"~"item key".
Naturally this means that retrievals for "namespace key" are very frequent, for each namespaced get/set/etc request. Still this allows to easily invalidate many keys, by incrementing/changing "namespace key" value.

Trouble is that after upgrading php, and php-memcached, we sometimes somehow have a result of php-memcached -> get("namespace key") returning invalid value (some serialized object, but read on). Needless to say over last 4 days I looked a lot of things. Now biggest problem is that it only happens sometimes, hard to say how often. Still I logged around all our behavior quite a lot, and fail to see application logic failure. One most convincing test that shows me that this is php-memcached and not server issue, is that even when I get errors about invalid value for "namespace key", i get at most one such error per request (but again that "namespace key" is being retrieved multiple times on each request). However if I manually set "namespace key" to invalid value on servers (we have two memcached servers, using consisten hashing) I get like 5-10 notifications about invalid value, as value is really invalid.

One more thing, I have problem with "namespace keys" for some different namespaces, quite some. In any case for some I managed to "work around" this, which simply means where I had cases where I get values for "each row" one by one, I had many such errors, to improve the situation there (not only for cache, but also in case cache goes down and only db is used) I reworked those places to essentially cache whole (sub)table (as those tables are not very large), and store it php static var to not request data from db and/or cache, and I get no more errors from there, even though namespace is still used, but of course just couple of times per http request at most.

Now last thing, for those incorrect values, they seem to be one of fully namespaced values, so say I have calls like
urls_namespace~7~awesome_page_url it stores value 
"www.nicedomain.com/this_is_best_page_ever.html"
then next time (well presumably...) php memcached gets 
urls_namespace it also returns "www.nicedomain.com/this_is_best_page_ever.html" while it should return 7 .

So possibly there is some "internal caching" in phpmemcached, that checks if same key was requested recently and if so it does not make request to server? Well this is total speculation on may part, and disregard it if it is nonsense.

I know this is fairly vague, but it is all I have. I tried reproducing this with simple scripts, without whole application, but couldn't do it; I even tried looking at php-memcached C code, but I'm unfamiliar with php extension development, nether libmemcached, so was unable to have any meaningfull understanding of what is happening.

**Comment by sodabrew** [comment]
There is no internal caching in php-memcahced, no.

Based on your description is does not sound like you are issuing GET and SET commands to the same keys in rapid succession, which can result in wall-clock out of sequence responses due to multi threading (if a get request was queued before the delete request, that get request will return the old value before the delete is processed).

There is a bug fix that is unreleased in master branch that fixes a memory value release bug, this might be the issue for you.

**Comment by rickytato** [comment]
@morphles How big are items you store? We also have some strange issue that seems disappear started memcached with "-I 8m"

**Comment by morphles** [comment]
@rickytato yes after some wresting with bug I found that memcached protocol/server limits value size to 1MB by default, so though that might be issue. Told to server admin he increased memcached server value size (to 128M... but whatever), issue did not resolve. So it does not seem to be size related, though there is a possibility that certain objects we store might get close to 1MB or a bit over.

@sodabrew Thanks for you rather swift reply. No normally we should not be giving set requests for those "namespace keys" almost at all, it's only if admin edits some option title or something like that, which should be very rare indeed. So doubt that it is that wall clock issue too. Though it is good to be aware of such possibility.

As for that bug fix you mention, I was unable to find a commit looking at https://github.com/php-memcached-dev/php-memcached/commits/master , for me no description (after 3.0.3 which we use) matches your satament, though possibly [this](https://github.com/php-memcached-dev/php-memcached/commit/5f28025c15c87d0895f39def77068c8fd66d442a?diff=unified) is what you meant?

**Comment by sodabrew** [comment]
Please try memcached 3.0.4 to see if it resolves this problem:
https://pecl.php.net/package/memcached/3.0.4

**Comment by sodabrew** [comment]
Closing as presumed-fixed by the string variable release bugfix in 3.0.4
