### ISSUE TITLE
Memcached set failed when expiration time set

### ISSUE THREAD

**Issue by discripter** [php-memcached-dev/php-memcached#368]
Memcached every day throws a strange bug..

Code1:

```
$mc = new Memcached();
$mc->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$mc->addServer(API::MEMCHACHED_HOST, API::MEMCHACHED_PORT);

var_dump($mc->getResultCode(), $mc->getResultMessage()); 
echo "\n---------------\n";
var_dump($mc->set('807313365_lock', 1, time() + 60));
var_dump($mc->getResultCode(), $mc->getResultMessage());
echo "\n---------------\n";

var_dump($mc->get('807313365_lock'));
var_dump($mc->getResultCode(), $mc->getResultMessage());
```

```
int(0)
string(7) "SUCCESS"
---------------
bool(true)
int(0)
string(7) "SUCCESS"
---------------
bool(false)
int(16)
string(9) "NOT FOUND"
```

Code2:

```
$mc = new Memcached();
$mc->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$mc->setOption(Memcached::OPT_HASH, Memcached::HASH_CRC);
$mc->setOption(Memcached::OPT_SERVER_FAILURE_LIMIT, 3);
$mc->setOption(Memcached::OPT_RETRY_TIMEOUT, 1);
$mc->setOption(Memcached::OPT_NO_BLOCK, true);
$mc->setOption(Memcached::OPT_BUFFER_WRITES, true);
$mc->addServer(API::MEMCHACHED_HOST, API::MEMCHACHED_PORT);

var_dump($mc->getResultCode(), $mc->getResultMessage()); 
echo "\n---------------\n";
var_dump(time() + 60);
var_dump($mc->set('807313365_lock', 1, time() + 60));
var_dump($mc->getResultCode(), $mc->getResultMessage());
echo "\n---------------\n";
var_dump($mc->get('807313365_lock'));
var_dump($mc->getResultCode(), $mc->getResultMessage());
```

```
int(0)
string(7) "SUCCESS"
---------------
bool(true)
int(32)
string(13) "ACTION QUEUED"
---------------
bool(false)
int(16)
string(9) "NOT FOUND"
```

When I removed the expiration time, it worked again:

```
var_dump($mc->set('807313365_lock', 1));
var_dump($mc->getResultCode(), $mc->getResultMessage());
var_dump($mc->get('807313365_lock'));
var_dump($mc->getResultCode(), $mc->getResultMessage());
```

```
int(0)
string(7) "SUCCESS"
---------------
bool(true)
int(0)
string(7) "SUCCESS"
int(1)
int(0)
string(7) "SUCCESS"
```

Some info about memcached server:

```
> telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
stats
STAT pid 1175
STAT uptime 68219
STAT time 1505980019
STAT version 1.4.25 Ubuntu
STAT libevent 2.0.21-stable
STAT pointer_size 64
STAT rusage_user 42.544000
STAT rusage_system 222.392000
STAT curr_connections 6
STAT total_connections 80641
STAT connection_structures 15
STAT reserved_fds 20
STAT cmd_get 4668690
STAT cmd_set 101810
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 2158521
STAT get_misses 2510169
STAT delete_misses 18
STAT delete_hits 14858
STAT incr_misses 0
STAT incr_hits 17287
STAT decr_misses 0
STAT decr_hits 12153
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 389605219
STAT bytes_written 796249085
STAT limit_maxbytes 536870912
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT time_in_listen_disabled_us 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT malloc_fails 0
STAT bytes 120802
STAT curr_items 749
STAT total_items 107884
STAT expired_unfetched 1189
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 4142
STAT crawler_reclaimed 0
STAT crawler_items_checked 0
STAT lrutail_reflocked 6

```
```
> netstat -tap | grep memcached               
tcp        0      0 localhost:11211         *:*                     LISTEN      1175/memcached
tcp        0      0 localhost:11211         localhost:60056         ESTABLISHED 1175/memcached
```

After restarting the memcached, it works again normally.. And all threads works fine.

```
netstat -tap | grep memcached
tcp        0      0 localhost:11211         *:*                     LISTEN      5680/memcached
tcp        0      0 localhost:11211         localhost:34698         ESTABLISHED 5680/memcached
tcp        0      0 localhost:11211         localhost:34346         ESTABLISHED 5680/memcached
tcp        0      0 localhost:11211         localhost:34738         ESTABLISHED 5680/memcached
```

Help to understand and repare this error. I don`t want to make a temporary solution - daily reboot of the memcache server.

**Comment by sodabrew** [comment]
What version of PHP and php-memcached are you using?

**Comment by sodabrew** [comment]
Instead of setting the expiration as `time() + 60` just set it to 60. Review the memcached documentation on this point: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L79

> Expiration times
>----------------
>
>Some commands involve a client sending some kind of expiration time
(relative to an item or to an operation requested by the client) to
the server. In all such cases, the actual value sent may either be
Unix time (number of seconds since January 1, 1970, as a 32-bit
value), or a number of seconds starting from current time. In the
latter case, this number of seconds may not exceed 60*60*24*30 (number
of seconds in 30 days); if the number sent by a client is larger than
that, the server will consider it to be real Unix time value rather
than an offset from current time.

**Comment by discripter** [comment]
> What version of PHP and php-memcached are you using?

```
memcached -V
memcached 1.4.25

```

php -v
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies


phpinfo(): [Image](https://snag.gy/fHi0jX.jpg)

**Comment by discripter** [comment]
> Based on this description, I suspect the time on your memcached client machine is more than one minute different than your memcached server, and so the object is immediately expired.

Tnx for advise, Aaron!
Please tell me why the working capacity of my code is restored after the restart of the service? And why is this drop observed every day?
The time on my server is UTC..

**Comment by sodabrew** [comment]
Apologies for the long delay to reply.

If you're rebooting the entire memcached server, it's probably syncing the time via `ntpdate` as an init script, and then slowly drifting to be more than 1 minute different some time later in the same.

Try setting up `ntpd` to run on your servers to keep their time synced continuously and see if this helps?

**Comment by sodabrew** [comment]
Also if you set the cache expiration to be relative, i.e. `60` instead of exact, `time() + 60` then you won't be affected by a time difference between the servers.

**Comment by crhg** [comment]
Because memcached internally uses a clock based on the monotonic clock, the time of memcached is different from the time of the real world. This is to avoid confusion of expire time when time adjustment is done by ntp etc.

The internal clock of memcached is equal to wall clock at startup, but generally the difference will become bigger as the time from startup becomes longer.

The internal clock of memcached can be known with the `stats` command. If memcached has been running for a long time since startup, you will find that there is considerable difference from the current time.

```terminal
% telnet localhost 11211
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
stats
STAT pid 1
STAT uptime 103
STAT time 1516412108       <--- here
STAT version 1.5.4
...
```

When expiration time is given with unix timestamp, it is interpreted by memcached 's internal clock, so it is different from the time of the real world. In order to avoid this problem, it is desirable to specify it in seconds rather than unix timestamp when the expiretion period is short.

**Comment by sodabrew** [comment]
Thank you very much for the definitive explanation!
