### ISSUE TITLE
Session Remains Locked after hitting Error in 3.0.3

### ISSUE THREAD

**Issue by fishfacemcgee** [php-memcached-dev/php-memcached#370]
I'm not certain this is related to #269 as it's happening even after applying the fixes (config updates) discussed in that thread, which did make a significant improvement except for this continued issue. If the consensus is that this belongs in there, I'm fine with that.

# Problem Description
We're in the process of testing a PHP 5.6 -> PHP 7.1 upgrade. As best as I can tell, when a web request with a locked session hits a PHP Error and causes the request to end, it does not successfully free up the session lock. This means that all future requests after that Error is hit have to wait for the session to expire on its own. I expect for most users of this extension this is fine, but for our set up, our max execution time is 5 minutes, meaning hitting an error in our app blocks you from using the rest of the app for 5 minutes. I've also confirmed that this is the case when I use [`session_register_shutdown`](http://php.net/manual/en/function.session-register-shutdown.php).

# Environment Details
* PHP Version: 7.1.9
* php-memcached: 3.0.3
* libmemcached: 1.0.16

# Memcached Extension Config Values
* memcached.compression_factor: 1.3
* memcached.compression_threshold: 2000
* memcached.compression_type: fastlz
* memcached.default_binary_protocol: no value
* memcached.default_connect_timeout: 0
* memcached.default_consistent_hash: no value
* memcached.serialize: igbinary
* memcached.sess_binary_protocol: no value
* memcached.sess_connect_timeout: 1000
* memcached.sess_consistent_hash: 1
* memcached.sess_lock_expire: 0
* memcached.sess_lock_max_wait: not set
* memcached.sess_lock_retries: 2000
* memcached.sess_lock_wait: not set
* memcached.sess_lock_wait_max: 150
* memcached.sess_lock_wait_min: 150
* memcached.sess_locking: 1
* memcached.sess_number_of_replicas: 0
* memcached.sess_persistent: no value
* memcached.sess_prefix: memc.sess.key.
* memcached.sess_randomize_replica_read: no value
* memcached.sess_remove_failed_servers: no value
* memcached.sess_sasl_password: no value
* memcached.sess_sasl_username: no value | no value
* memcached.sess_server_failure_limit: 0
* memcached.store_retry_count: 2

# Session Config Values
* session.auto_start: Off
* session.cache_expire: 180
* session.cache_limiter: nocache
* session.cookie_domain: no value
* session.cookie_httponly: On
* session.cookie_lifetime: 0
* session.cookie_path: /admin/
* session.cookie_secure: On
* session.gc_divisor: 1000
* session.gc_maxlifetime: 1440
* session.gc_probability: 1
* session.lazy_write: Off
* session.name: PHPSESSID
* session.referer_check: no value
* session.save_handler: memcached
* session.save_path: redacted
* session.serialize_handler: php
* session.sid_bits_per_character: 4
* session.sid_length: 32
* session.upload_progress.cleanup: On
* session.upload_progress.enabled: On
* session.upload_progress.freq: 1%
* session.upload_progress.min_freq: 1
* session.upload_progress.name: PHP_SESSION_UPLOAD_PROGRESS
* session.upload_progress.prefix: upload_progress_
* session.use_cookies: On
* session.use_only_cookies: On
* session.use_strict_mode: Off
* session.use_trans_sid: 0

**Comment by fishfacemcgee** [comment]
Quick note. From some further testing, I've found that enabling `session.lazy_write` appears to alleviate the issue. However, I saw other suggestions/recommendations to disable `session.lazy_write` since it could force the binary protocol to get enabled which isn't recommended on libmemcached < 1.0.18. Is that not still relevant?

**Comment by woolardfa** [comment]
Trying to replicate the problem using a call to require_once() with invalid filename, but lock entry is removed as part of the built-in session clean up. What particular type of error occurs?

This discussion involving lazy write might provide some insights? https://tracker.moodle.org/browse/MDL-57477?focusedCommentId=451229&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-451229

**Comment by fishfacemcgee** [comment]
@woolardfa The error I've hit that seems to cause the issue is the new ArgumentCountError in PHP 7.1. I might be misinterpreting the core issue. When I was stracing, it looked like the key was being deleted, but all future requests would hang until the 5 minute session expiration had been hit. I'll double-check and report back.

Reading more on the lazy_write stuff that you provided is interesting. We did start seeing some slower requests after enabling lazy_write, but that somehow alleviated this other lock issue. I'll keep digging through and see if anything helps explain the behavior.

**Comment by fishfacemcgee** [comment]
I'm going to go ahead and close this for now. I unfortunately don't have the time to do in-depth debugging on the core issue, but turning on lazy_write (with binary protocol disabled) appears to solve, or at least work around, the issue for me.
