### ISSUE TITLE
window system use  php-memcached library

### ISSUE THREAD

**Issue by Forever1Love** [php-memcached-dev/php-memcached#371]
My computer system is window ,how can I use php-memcached library,how can I use these files to generate  php-memcached.dll for window platform.
And how can I use php-memcached with libmemcached.

**Comment by sodabrew** [comment]
This extension is not distributed as a Windows binary at this time. I would welcome a contribution of code to generate Windows binaries in the future.

https://secure.php.net/manual/en/install.pecl.windows.php
