### ISSUE TITLE
failure to compile on red hat enterprize 6

### ISSUE THREAD

**Issue by js0000** [php-memcached-dev/php-memcached#373]
hi

i'm trying to compile memcached pecl without success. any help is welcome.

here's the host and php specifications
# uname -a
Linux <HOSTNAME> 2.6.32-696.10.1.el6.x86_64 #1 SMP Wed Jul 19 08:18:21 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
# php --version
PHP 7.1.11 (cli) (built: Oct 27 2017 14:46:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies

i'm attachine the output of the "make" command, which does not complete.
[memcached-compile-error.txt](https://github.com/php-memcached-dev/php-memcached/files/1536584/memcached-compile-error.txt)

**Comment by sodabrew** [comment]
Your version of libmemcached may be too old.

**Comment by js0000** [comment]
thx, i'll see what i can do about updating that
