### ISSUE TITLE
How to work with PHP 7.1 in windows 7

### ISSUE THREAD

**Issue by radision** [php-memcached-dev/php-memcached#374]
I used xampp in windows 7, but I could not found the memcached extension for PHP 7.1, called php_memcached.dll, how can I do that?

**Comment by sodabrew** [comment]
A Windows binary is not provided for this extension. You would need to compile your own. Here's a starting point for installing a PECL extension on Windows:

https://secure.php.net/manual/en/install.pecl.windows.php

This extension relies on the libmemcached library, here's starting points for compiling that as well:

https://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.0/view/head:/README.win32
https://github.com/yshurik/libmemcached-win

Best luck!

**Comment by radision** [comment]
thx a lot!
