### ISSUE TITLE
session not shared between memcache and memcached save handler

### ISSUE THREAD

**Issue by lichunqiang** [php-memcached-dev/php-memcached#377]
Scenario:

our passport server is old php5.5.9 and used the memcache as save handler

web server is upgraded to php7.1.0 and used the memcached as save handler.

The only different is `session.save_path`.  memcache  with `tcp://` prefix and memcached without the prefix, but the server group is the same.

After test.  found that, set a session data in memcache(php5) env but can not get in memcached(php7) version

**Comment by sodabrew** [comment]
There would be two issues, the first is ensuring the same cache keys generated from both extensions, and the second if you have a pool of memcached servers, is to have the same hash distribution of keys to servers.

**Comment by lichunqiang** [comment]
Session id is the same, but it is the cache is the same/

**Comment by bny6613** [comment]
Check if your session prefixes are the same -  memcached.sess_prefix option. Session key is generated as memcached.sess_prefix + session_id.
session.serialize_handler should also be the same in both configurations.

**Comment by lichunqiang** [comment]
thanks all.
