### ISSUE TITLE
memcached.sess_number_of_replicas config is not working

### ISSUE THREAD

**Issue by rossoneri** [php-memcached-dev/php-memcached#382]
Whatever value I set `memcached.sess_number_of_replicas` to , the session data is saved in one server only!

Env: centos7+php7.2.1

**Comment by bny6613** [comment]
Can you provide your ini settings? Make sure that you have memcached.sess_binary_protocol enabled, otherwise replication will not work.

**Comment by rossoneri** [comment]
@bny6613 thank you! It's the problem of memcached.sess_binary_protocol setting.
