### ISSUE TITLE
Expose build configuration via PECL

### ISSUE THREAD

**Issue by bsacharski** [php-memcached-dev/php-memcached#383]
It would seem that many of build configuration options like `--enable-memcached-igbinary `, `--enable-memcached-msgpack` and so on are not exposed as a PECL configuration option. Maybe it would be wise to expose them in `package.xml` file so it's possible to configure them in a nice manner.

**Comment by sodabrew** [comment]
Interesting! I'm not familiar with these options. Thanks for suggesting. Looks like the relevant PECL docs are here: https://pear.php.net/manual/en/guide.developers.package2.pecl.php
