### ISSUE TITLE
Memcached::OPT_COMPRESSION always returns -1001 (RES_PAYLOAD_FAILURE)

### ISSUE THREAD

**Issue by futureweb** [php-memcached-dev/php-memcached#384]
Hello,

on multiple Servers I get -1001 for Memcached::OPT_COMPRESSION
Shouldn't Memcached::OPT_COMPRESSION be BOOL - if compress is activated or not?

System: CentOS Linux release 7.4.1708 (Core) 
PHP: 7.2.2
memcached: 3.0.4
memcached Server: 1.5.5

Any ideas on that?

thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by sodabrew** [comment]
The value is defined here: https://github.com/php-memcached-dev/php-memcached/blob/e0ccf87c517bc3ec54067166d34058f21d67b0b3/php_memcached.c#L68

What is the problem you are trying to solve?

**Comment by futureweb** [comment]
Hey @sodabrew,
according to http://php.net/manual/en/memcached.constants.php I would expect a BOOL as return - if compression is activated or deactivated - are the Docs wrong, or do I missunderstand something here?

> Memcached::OPT_COMPRESSION
> 
>     Enables or disables payload compression. When enabled, item values longer than a certain threshold (currently 100 bytes) will be compressed during storage and decompressed during retrieval transparently.
> 
>     Type: boolean, default: TRUE.


And how to check then if compression is activated or not?
thx

**Comment by sodabrew** [comment]
> Shouldn't Memcached::OPT_COMPRESSION be BOOL - if compress is activated or not?

No, that's a constant. You can get/set the compression option like this:

```
$m = new Memcached();

$m->setOption(Memcached::OPT_COMPRESSION, false);

$isCompressed = $m->getOption(Memcached::OPT_COMPRESSION);
```

**Comment by futureweb** [comment]
ok - my bad - makes definately sense - thx for clarification ;-)
