### ISSUE TITLE
 lvalue required as left operand of assignment    GC_REFCOUNT(&le) = 1;

### ISSUE THREAD

**Issue by tekintian** [php-memcached-dev/php-memcached#385]
when build with the latest php version  https://github.com/php/php-src .

 error: lvalue required as left operand of assignment

php_memcached.c . 	line 1301:   	

GC_REFCOUNT(&le) = 1;

php_memcached_session.c:379:20: error: lvalue required as left operand of assignment
   GC_REFCOUNT(&le) = 1;
                    ^
make: *** [php_memcached_session.lo] Error 1

------

/tmp/php-memcached-master/php_memcached_session.c: In function 'ps_open_memcached':
/tmp/php-memcached-master/php_memcached_session.c:379:20: error: lvalue required as left operand of assignment
   GC_REFCOUNT(&le) = 1;
                    ^
make: *** [php_memcached_session.lo] Error 1
Makefile:202: recipe for target 'php_memcached_session.lo' failed

**Comment by sodabrew** [comment]
Was this problem resolved? Is this something I'll need to handle for an upcoming 7.x release?

**Comment by tekintian** [comment]
I have found my issue is similar this https://github.com/php-memcached-dev/php-memcached/issues/385, 
And I have just delete this line " GC_REFCOUNT(&le) = 1; "   in  php_memcached_session.c  and php_memcached.c

build it sucess

Here is the php-7.3-dev for docker  https://hub.docker.com/r/tekintian/php/

**Comment by sodabrew** [comment]
Found it, this is a documented change in the API for PHP 7.3: https://github.com/php/php-src/blob/master/UPGRADING.INTERNALS#L78

**Comment by tekintian** [comment]
That's great, thanks!
