### ISSUE TITLE
can't send sasl auth without username

### ISSUE THREAD

**Issue by xiaoliwang** [php-memcached-dev/php-memcached#387]
```php
$memcache->setSaslAuthData($username, $password);
```
if I set `$username = null` or `$username = ''`. I can't catch sasl auth request.

**Comment by sodabrew** [comment]
It should work. Please provide more information to help debug this problem.

**Comment by xiaoliwang** [comment]
1.cap with username.
2.cap without username
[6e11a15a-f8f2-40ab-8e3d-97e403b79b1f.zip](https://github.com/php-memcached-dev/php-memcached/files/1889179/6e11a15a-f8f2-40ab-8e3d-97e403b79b1f.zip)
