### ISSUE TITLE
[question]removed failed server can be recovered automatically?

### ISSUE THREAD

**Issue by lichunqiang** [php-memcached-dev/php-memcached#388]
```
; Allow failed memcached server to automatically be removed.
; Default is Off. (In previous versions, this setting was called memcached.sess_remove_failed)
;memcached.sess_remove_failed_servers = Off

; Set this value to enable the server be removed after
; configured number of continuous times connection failure.
;memcached.sess_server_failure_limit = 0
```

For this configuration, If one server is removed, it can be recovered automatically when the server is alive again.

**Comment by sodabrew** [comment]
It's a reasonable question, I'm not sure of the answer. The underlying behavior in libmemcached may be better documented in their API docs. http://docs.libmemcached.org/memcached_behavior.html?highlight=remove#MEMCACHED_BEHAVIOR_REMOVE_FAILED_SERVERS

**Comment by lichunqiang** [comment]
> If enabled any hosts which have been flagged as disabled will be removed from the list of servers in the memcached_st structure.

It's init session save handlers after call `session_start`, Right?

So, The behavior (remove the failure server) belong a request, not the whole php-fpm life circle.

Do I have an exact understanding? Wating your opinion.

Thanks.

**Comment by sodabrew** [comment]
session can be persistent or not persistent. If the session is persistent, the lifecycle is the php-fpm process. If the session is not persistent, the lifecycle is each request. The choice is made in the `memcached.sess_persistent = On / Off` INI value.

**Comment by lichunqiang** [comment]
Got it, Thanks for your replay @sodabrew .
