### ISSUE TITLE
Does UDP connect really work?

### ISSUE THREAD

**Issue by arkhamvm** [php-memcached-dev/php-memcached#389]
```
$m_udp = new Memcached();
$m_udp->setOption(Memcached::OPT_USE_UDP, true);
$m_udp->addServer('127.0.0.1', 11211, 1);
var_dump($m_udp->getResultMessage());
var_dump($m_udp->getServerList());
```

```
string(7) "SUCCESS" 
array(1) { [0]=> array(3) { 
    ["host"]=> string(9) "127.0.0.1" 
    ["port"]=> int(11211) 
    ["type"]=> string(3) "TCP" 
} }
```

Is it normal that server "type" still "TCP" ?

**Comment by arkhamvm** [comment]
Also:
```
$m_udp->get('somekey');
var_dump($m_udp->getResultMessage());
```

```
string(20) "ACTION NOT SUPPORTED"
```

**Comment by sodabrew** [comment]
`"ACTION NOT SUPPORTED"` indicates you're using the wrong protocol - UDP only supports the ASCII protocol, not BINARY.

**Comment by arkhamvm** [comment]
@sodabrew, still doesn't work:
```
$m_udp = new Memcached();
$m_udp->setOption(Memcached::OPT_USE_UDP, true);
$m_udp->setOption(Memcached::OPT_BINARY_PROTOCOL, false);

$m_udp->addServer('127.0.0.1', 11211, 1);
var_dump($m_udp->getResultMessage());

$m_udp->get('somekey');
var_dump($m_udp->getResultMessage());
```
```
string(7) "SUCCESS" 
string(20) "ACTION NOT SUPPORTED"
```

**Comment by sodabrew** [comment]
Confirmed, the code always uses `memcached_mget` even for simple gets, and UDP does not support mget.

**Comment by sodabrew** [comment]
http://docs.libmemcached.org/memcached_behavior.html

> Causes libmemcached(3) to use the UDP transport when communicating with a memcached server. Not all I/O operations are testsed when this behavior is enababled. The following operations will return MEMCACHED_NOT_SUPPORTED when executed with the MEMCACHED_BEHAVIOR_USE_UDP enabled: memcached_version(), memcached_stat(), memcached_get(), memcached_get_by_key(), memcached_mget(), memcached_mget_by_key(), memcached_fetch(), memcached_fetch_result(), memcached_fetch_execute().

Turns out this is expected behavior.

**Comment by arkhamvm** [comment]
That's sad.
Thank you for explanation.
