### ISSUE TITLE
pecl install fails with rhel6 and php7

### ISSUE THREAD

**Issue by js0000** [php-memcached-dev/php-memcached#391]
trying to install this exension on my rhel6 system without success. the compilation fails. i'm attaching a log of the process for your review. please feel free to ask for more data or to make suggestions as to how i will be able to install. thx.
[phpMemcached-install-fail.txt](https://github.com/php-memcached-dev/php-memcached/files/1860836/phpMemcached-install-fail.txt)

**Comment by sodabrew** [comment]
The minimum supported version of libmemcached is 1.0.x

**Comment by sodabrew** [comment]
Can you check the version of libmemcached you have installed, and if you're able to find a newer version that's appropriate for your system?

**Comment by js0000** [comment]
thank you- that was it exactly. i upgraded libmemcached to a version > 1.0 and it all was just fine. thank you! this can be closed (as you know, this is actually already in the docs- i just missed it, sorry!)
