### ISSUE TITLE
How to run tests with shared session extension

### ISSUE THREAD

**Issue by petk** [php-memcached-dev/php-memcached#397]
Hello,

From my understanding, the PHP memcached extension requires the [core PHP session extension](https://github.com/php/php-src/tree/master/ext/session) to be present. And of course also when running tests via `make test` command.

However, the generated Makefile for the PHP memcached extension removes all configurations with `-n` option. So when the session extension is present on the system doing the tests via the shared object (not compiled statically into php cli binary) `session.so`, the tests can't be run. The following warning happens:

```text
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/memcached-3.0.4/modules/memcached.so' - Error relocating /opt/memcached-3.0.4/modules/memcached.so: php_session_create_id: symbol not found in Unknown on line 0
```

Is there any workaround how this should be handled in such cases? 

Above example is happening on Alpine where goal is to split all packages into as little subpackages as possible, so therefore the php session extension as a shared object.

**Comment by sodabrew** [comment]
At the command line, you can tell PHP to load extensions, for example:

```
php -d extension=session.so -d extension=memcached.so run_tests.php
```

**Comment by petk** [comment]
Thank you so much for your help. Closing this missed question then... 😄
