### ISSUE TITLE
setMulti failed to set key, set works normal?

### ISSUE THREAD

**Issue by duronrulez** [php-memcached-dev/php-memcached#409]
As the title says, when we're using "setMulti" at some point (randomly?) the memcached lib starts spitting out "failed to set key" warnings. While when we use "set" its all normal and works fine all the time. 

Is there any difference in the implementation of setMulti and set? From what i understand (havent read the code) under the hood setMulti is doing a cycle and running set anyway?

**Comment by Krinkle** [comment]
This warning is logged by `Memcached::setMulti` when the `s_memc_write_zval()` call for one of the keys returns false, which presumably means Memcached was unable to store that key ([source code](https://github.com/php-memcached-dev/php-memcached/blob/v3.0.1/php_memcached.c#L1824)). This is not uncommon and could happen for a number of reasons such as value being too large, unable to be serialized, a timeout, temporary connection issue perhaps, etc.

This warning was added to `setMulti` in commit a930b41 (pull request #214), first released in php-memcached 3.0.0 and generally used alongside PHP 7.

The `Memcached::set()` method uses that same `s_memc_write_zval()` function for storing data, but when it returns false there, no warning is logged in response. So..., I guess the take-away here is that the library has **not regressed** in php-memcached 3.0.0, and that `setMulti` is **not buggy**. It's just that setMulti logs a warning for a seemingly normal runtime condition when storing a key fails, whereas other methods of storing a key do not log such warning.

I do note that the details of these error scenarios are available via `::getResultCode` and `::getResultMessage`, and this hasn't changed in recent years. Any code you have in place for finding and reporting such background errors will work fine regardless of this setMulti warning. It seems like this was perhaps just added by mistake in #214 and could be removed in in a future release. As a workaround, to improve error signal in your application, one could suppress this warning by using the [error control operator](https://www.php.net/manual/en/language.operators.errorcontrol.php) specifically when calling `setMulti()`.

_Downstream issue for Wikimedia Foundation: [T251450](https://phabricator.wikimedia.org/T251450)._
