### ISSUE TITLE
php7 memcached extension not compatible hhvm memcached 

### ISSUE THREAD

**Issue by serverglen** [php-memcached-dev/php-memcached#412]
log info:
PHP Warning: Memcached::get(): could not decompress value: unrecognised compression type

**Comment by sodabrew** [comment]
Please add enough information to do anything with this ticket.

If you're asking for me to do the work of making this compatible across two implementations for you, no, I won't do that.

I would be glad to review a pull request if you do the work!

**Comment by sodabrew** [comment]
Closing due to lack of information.
