### ISSUE TITLE
Object missing...

### ISSUE THREAD

**Issue by jamespanda** [php-memcached-dev/php-memcached#414]
While I get an object from memcache and then get again(in different php file)...it return null...
My misunderstanding?(memcached)

my code...
  function connectMemcache() {
    $memcache = new Memcached();
    $memcache->setOption(Memcached::OPT_COMPRESSION, false);
    $memcache->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
    $memcache->setOption(Memcached::OPT_TCP_NODELAY, true);
    $memcache->addServer('localhost', 11211) or die ("Could not connect");
    return $memcache;
  }

  function setLang() {
    $memcache = connectMemcache();
    $lang = $memcache->get("lang");
    if ($lang == null) {
      $lang = new lang();
      $memcache->set("lang", $lang, 0);
    }
  }

  function getLang() {
    $memcache = connectMemcache();
    return $memcache->get("lang");
  }

**Comment by sodabrew** [comment]
This is a working example. If it's not working, you'll need to debug your situation. Work through each step. Is `new lang();` returning the object you expect? Is it getting serialized in the format you expect? Can you connect to memcached with `nc` (netcat) and fetch objects manually by the ascii protocol? Does memcached's `stats` method indicate that your code is incrementing the set / get counters? If not, is your code failing to talk to memcached in the first place? If not why not?

**Comment by sodabrew** [comment]
Do you need any further help?
