### ISSUE TITLE
Some problem with php7.3

### ISSUE THREAD

**Issue by bscheshirwork** [php-memcached-dev/php-memcached#425]
I have problem like 
https://stackoverflow.com/questions/31699056/php-fpm-child-process-exited-on-signal-11

on php 7.3 for this dockerfile https://github.com/bscheshirwork/docker-php/blob/3219c344ca8daf55e2fda5cd6898b3b02a7dce10/yii2-alpine-xdebug/Dockerfile#L50-L54

nginx produced 502 error with log
```
2019/01/09 12:25:50 [error] 8#8: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client ...
```

docker-compose logs
```
php_1             | [09-Jan-2019 12:25:50] WARNING: [pool www] child 9 exited on signal 11 (SIGSEGV - core dumped) after 55.035600 seconds from start
php_1             | [09-Jan-2019 12:25:50] NOTICE: [pool www] child 20 started
```

Unfortunately, I could not make a coredump for php-fpm, but I still open the task

**Comment by sodabrew** [comment]
Because the dockerfile is building pho-memcached from source from the head of the got repo, I cannot be sure what code revision you’re using and therefore whether a bug has been fixed relevant to this problem.

Please update the dockerfile to use the latest published version of php-memcached extension to help pinpoint the issue.

**Comment by bscheshirwork** [comment]
I build this image at 12 h ago and published on docker hub. This problem will be starting with previous build (I try it in prev month on first major versions of memcached)

**Comment by bscheshirwork** [comment]
this image is 
bscheshir/php:fpm-alpine-4yii2-xdebug
bscheshir/php:7.3.0-fpm-alpine-4yii2-xdebug

digest: sha256:71bbca19c16e65513487346a4a8abae54cd5901c3d0bc3c2dec79514032cdf06 size: 3252

I try to rebuild this now. The sha is same to yesterday

**Comment by bscheshirwork** [comment]
Upd: I will rebuild image for new minor version of php:

bscheshir/php:7.3.1-fpm-alpine-4yii2-xdebug
digest: sha256:dcb0c8330094cc52253fda4bc1bf423ac67abe7a831ac375cd44b2b124107006 size: 3252

same situation

**Comment by bscheshirwork** [comment]
So... Look like general problem or xdebug problem, not memcached

**Comment by bscheshirwork** [comment]
[14941.716068] php-fpm[4766]: segfault at ffffffffffffff02 ip 000055bddfea3467 sp 00007ffc1ae235f8 error 7 in php-fpm[55bddfd77000+d5a000]

**Comment by bscheshirwork** [comment]
This is opcache error on php 7.3.0 and 7.3.1
I add "opcache.optimization_level=0x7FFFBBFF" into php.ini 

and all is work

Thanks for Derick from IRC chanel #xdebug
