### ISSUE TITLE
windows7 compile error 

### ISSUE THREAD

**Issue by lifenglsf** [php-memcached-dev/php-memcached#430]
libmecached vs2017 compiled
```
 configure --disable-all --enable-cli --enable-memcached --disable-zts
```
configure success,nmake failed
error message:
```

  正在创建库 D:\phpwindows\php-sdk-binary-tools\bin\php7.2_x86\vc15\x86\php-
16-src\Release\php_memcached.lib 和对象 D:\phpwindows\php-sdk-binary-tools\b
hp7.2_x86\vc15\x86\php-7.2.16-src\Release\php_memcached.exp
php_memcached.obj : error LNK2019: 无法解析的外部符号 _compress，该符号在函数
_compress_value 中被引用
php_memcached.obj : error LNK2019: 无法解析的外部符号 _uncompress，该符号在函
_s_memcached_result_to_zval 中被引用
D:\phpwindows\php-sdk-binary-tools\bin\php7.2_x86\vc15\x86\php-7.2.16-src\Re
e\php_memcached.dll : fatal error LNK1120: 2 个无法解析的外部命令
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio
7\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe"”: 返回代码“
60”
Stop.
```
if i enable memcached_session,session not found: session support in memcached disabled

**Comment by sodabrew** [comment]
I don’t have bandwidth to sort out windows builds for this project. I am more than glad to review and integrate a PR.

The error indicates a missing library, probably zlib. Try configuring without it?

**Comment by lifenglsf** [comment]
I get code `ZEXTERN int ZEXPORT compress OF((Bytef *dest,   uLongf *destLen,
                                 const Bytef *source, uLong sourceLen));` from zlib.h

**Comment by lifenglsf** [comment]
`configure --enable-cli --enable-memcached --disable-zts` worked
Do not use disable-all
