### ISSUE TITLE
MemcachePool::getstats Allowed memory size exhausted Error

### ISSUE THREAD

**Issue by nareshpidatala** [php-memcached-dev/php-memcached#438]
Hi

Once we upgrade our site from PHP 5.3 to PHP 7.1.17, intermittently we are observing below error.

E_ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4294967288 bytes) in MemcachePool::getstats called at 

Full issue description is in https://www.drupal.org/project/memcache/issues/3034083

We are in 3.0.3 version.

Full PHP configurations are in attached ZIP file. Could you please help us to see if we need any configuration tweak.
[PHP-info.zip](https://github.com/php-memcached-dev/php-memcached/files/3182118/PHP-info.zip)

**Comment by sodabrew** [comment]
Please try with the most recent version of pho-memcached.

**Comment by nareshpidatala** [comment]
thanks for that, yes, we are upgrading to latest version 7.1.3
I will update here once we test it.

**Comment by nareshpidatala** [comment]
hi @sodabrew 

with memcached latest version of 3.1.3, we are still seeing the error. Any thing else we need to look out for in terms of memcached settings

**Comment by aryashreep** [comment]
the same issue is reported in PHP community https://bugs.php.net/bug.php?id=78103 and in the new release(PHP 7.2.19) it is fixed.
https://www.php.net/ChangeLog-7.php#7.2.19
