### ISSUE TITLE
Unable to use persistent connections to memcache

### ISSUE THREAD

**Issue by tagirb** [php-memcached-dev/php-memcached#439]
Recently started using php-pecl-memcached 3.1.3 on PHP 7.2 and currently trying to enable persistent connections to the Memcached servers. Although `Memcached()` constructor is called in the PHP code with a static ID, the Memcached servers report a considerably varying number of connections. It seems to me therefore that the connection is not persistent.

Looking through the code of `Memcached::__construct()` in the `php_memcached.c` I found out a weird thing in this snippet:
https://github.com/php-memcached-dev/php-memcached/blob/dd7e137da4c3534bf44f651fd5afdd77e67ed80c/php_memcached.c#L1238-L1265

The code fetches the pointer to the persistent memcached structure and saves it into the `intern->memc`:
https://github.com/php-memcached-dev/php-memcached/blob/dd7e137da4c3534bf44f651fd5afdd77e67ed80c/php_memcached.c#L1246

However, the following code does initialize the `intern->memc` **again** without checking whether it's been initialized already:
https://github.com/php-memcached-dev/php-memcached/blob/dd7e137da4c3534bf44f651fd5afdd77e67ed80c/php_memcached.c#L1255-L1260

Could you please check if that is a correct behavior?

**Comment by sodabrew** [comment]
That’s a bug for sure! Good find!

Thinking about how to write a test for this. Would want either a socket fd number or memcached connection id stat value to confirm that in persistent mode the same connection is reused.

**Comment by n10ty** [comment]
> The code fetches the pointer to the persistent memcached structure and saves it into the `intern->memc`:
> However, the following code does initialize the `intern->memc` **again** without checking whether it's been initialized already:

Look at 
https://github.com/php-memcached-dev/php-memcached/blob/dd7e137da4c3534bf44f651fd5afdd77e67ed80c/php_memcached.c#L1244-L1251
There is a **return** after structure found

**Comment by tagirb** [comment]
Yep, totally missed that. Thanks for pointing out!

**Comment by wwwebc** [comment]
The problem still persists!
