### ISSUE TITLE
Remove `latest release` label from older release

### ISSUE THREAD

**Issue by ruudk** [php-memcached-dev/php-memcached#447]
Better to not use the feature, or keep it up to date as it is a bit confusing.

<img width="992" alt="Image 2019-12-03 at 9 24 32 PM" src="https://user-images.githubusercontent.com/104180/70086874-8896df00-1613-11ea-82ce-7026f86381fc.png">

**Comment by sodabrew** [comment]
Oh, it's because I didn't create a Release to match the tag. It's not a feature I can turn off, that I can see in the GitHub interface.

**Comment by ruudk** [comment]
Ah like that. Weird Github bug then :(
