### ISSUE TITLE
Unable to set port=0 on php 7.4.7

### ISSUE THREAD

**Issue by xobotyi** [php-memcached-dev/php-memcached#459]
**Describe the bug**
Attempt to set server port to 0 defaults port to 11211.

**To Reproduce**
```php
$m = new \Memcached();
$m->addServer('unix:///var/run/memcached/memcached.socket', 0);
var_dump($m->getServerList()); // array(1) { [0]=> array(3) { ["host"]=> string(42) "unix:///var/run/memcached/memcached.socket" ["port"]=> int(11211) ["type"]=> string(3) "TCP" } }
```

module info:
```

memcached support | enabled
Version | 3.1.5
libmemcached version | 1.0.18
SASL support | yes
Session support | yes
igbinary support | yes
json support | yes
msgpack support | yes

**Comment by xobotyi** [comment]
So for now it is physically impossible to use memcached with sockets.

**Comment by sodabrew** [comment]
This unit test for this suggests that you would use a filename, not a URL spec, and that the port number can be default 11211 without a problem:

https://github.com/php-memcached-dev/php-memcached/blob/f4dafd207e4b3f1f54a7ce52194dda7cf40b0934/tests/experimental/addserver_unixdomain.phpt#L12-L16

**Comment by xobotyi** [comment]
But docs @php.net says that i should use 0 for unix sockets...

**Comment by m6w6** [comment]
I'm not sure, what the problem actually is. It is connecting fine to the unix socket, irrelevant what was specified or displayed as port.
