### ISSUE TITLE
increment(): Initial value is only supported with binary protocol

### ISSUE THREAD

**Issue by ghnp5** [php-memcached-dev/php-memcached#481]
I don't want to have Binary Protocol enabled.

If I do:

    $memcached->increment($key, $offset, $initial_value, $expire);

or:

    $memcached->increment($key, $offset, 0, $expire);

or:

    $memcached->increment($key, $offset, null, $expire);

I get this warning:

> PHP Warning [2]: Memcached::increment(): Initial value is only supported with binary protocol

If I do:

    $memcached->increment($key, $offset);

I don't get a warning.

How can I pass an $expire time without getting the warning?

And what's worst is that even if there is a value, it won't be incremented, if this warning triggers.

**Comment by sodabrew** [comment]
In the original text protocol, the "incr" command does not allow an initial value: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L344

There is a newer "meta arithmetic" command set that can increment with an initial value, but libmemcached does not support it:
https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L811

**Comment by ghnp5** [comment]
I understand and appreciate that.

However, I'm asking how do I set an Expire Time. Meaning, how can I skip the $initial_value parameter.

Thanks

**Comment by sodabrew** [comment]
Edited above to add:
What you can do is first call `$memcached->set($key, $value, $expiry)` and then `$memcached->increment($key, $amount)`

**Comment by ghnp5** [comment]
To me, that's not the solution, to be honest.

That makes it not atomic, which is the idea of "increment". I might as well just do a "get" and a "set" with +1, and we don't even need "increment" for anything.


My suggestion would be to do either of the following:

a) Provide a "setOption()" to suppress the warning, and have the "increment" method ignore $initial_value

b) Provide a new method, maybe called "incrementNonBinary($key, $offset, $expire)"

(or anything else that helps)


But forcing us to use "set()", just because we can't skip "initial_value", doesn't make sense to me.

**Comment by ghnp5** [comment]
Ah ok! Sorry - I thought "expiry" was available on increment, but "initial_value" was stopping me from setting "expiry".

Thank you for explaining. I understand now.
That's ok, then.

Thank you, and have a good day.

**Comment by ghnp5** [comment]
@sodabrew - By the way, as for the reason why I don't want to use binary protocol is because of performance on "get()" on a miss. (and I learned that binary protocol is going to be deprecated at some point)

See https://github.com/memcached/memcached/issues/775#issuecomment-801370073 for performance results.

**Comment by tobia** [comment]
@ghnp5 I stumbled onto the same limitation and I solved it by doing two operations:
```
$memcached->add($key, 0);
$memcached->increment($key, $offset);
```
If the key already exists, add() does nothing, otherwise it adds the key with value zero. Then the value is incremented.

This should be race-condition proof, because if other workers are running the same code concurrently for the same key, memcached will receive a sequence of add and increment operations. The sequence is guaranteed to start with an add, because each worker performs add before increment. The first add will add the key with value zero if not present; other add requests other than the first will do nothing; finally each increment call will increment the value atomically.

**Comment by ghnp5** [comment]
Thank you very much @tobia 

Actually, that's a very good suggestion, which I appreciate.

However, I was looking at the code I have around this, and seems that another limitation is that we cannot set an expiry timestamp, because of the `initial_value` parameter, so I'm actually forced to keep what I have, which is a `get` + `set`.

Sucks, and it's not race-condition proof, but...

I'm using `increment` only for non-critical things anyway.
