### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by remicollet** [php-memcached-dev/php-memcached#495]
Version 3.1.5 is very old (Dec 2019)

Lot of fixes have been applied in current code
especially PHP 8.0 / 8.1 compatibility

It will be nice to release a new version, and avoid users thinking this is a dead project.

**Comment by iCounsellorUK** [comment]
I second this.

Whilst many here will be able to do GitHub-things and wizz a newly compiled version of memcached onto our machines, applying all the readme patches as they go along (whatever 🤷🏻‍♂️) the rest of us are waiting for the signal that our 3.1.5 installations are ready to upgrade.

Sure - this thought might kick in your "BUT ITS EASY… YOU JUST *writes twenty instructions*" reactions, but that's not the point.

2019/3.1.5 is very old… doesn't (or can't figure how to) install in an 8.0/8.1 installation through, and needs you to do you those clever things that send all the fixes & improvements through our "for the almost layman" package managers, please 😁

**Comment by cmb69** [comment]
Related: #466

**Comment by Danack** [comment]
Hi @sodabrew @mkoppanen @andreiz ,

Would you guys be okay with me taking over maintaining this library?

I believe I have bona fides from maintaining Imagick (only 1 CVE so far), and some PHP core contributions.

cheers
Dan
Ack

p.s. Mikko - I have a slight sense of déjà vu...

**Comment by andreiz** [comment]
I don't mind

**Comment by ruudk** [comment]
@sodabrew Happy new year 🎆 Would it be possible to tag a new release? 🙏

**Comment by ruudk** [comment]
@krakjoe I see that you are also a maintainer, would you be able to help out? 🙏

**Comment by meinemitternacht** [comment]
@sodabrew @krakjoe @ruudk @mkoppanen @andreiz
Any updates on this? What needs to be done before the next release (3.1.6 or 3.2.0) ?

**Comment by krakjoe** [comment]
@remicollet you should have permissions to move forward, sorry about the delay ...

**Comment by lifenglsf** [comment]
> Version 3.2.0RC1 is released

windows support,nice

**Comment by ruudk** [comment]
Thanks for the RC versions. We are running them in production on PHP 8.1 on a high traffic website and it all seems to work great 🎉  When can we expect a final (non RC) release?

**Comment by remicollet** [comment]
2 weeks for RC seems a minimal delay to give testers a chance to report issues.

> We are running them in production on PHP 8.1 on a high traffic website and it all seems to work great

But of course, such **good** feedback is also very important, before pushing the GA version

**Comment by remicollet** [comment]
3.2.0 is released

**Comment by lifenglsf** [comment]
> 3.2.0 is released

only tags?

**Comment by cmb69** [comment]
No, also a new release: https://pecl.php.net/package/memcached/3.2.0

**Comment by m6w6** [comment]
I guess the GP comment is about not "publishing" the tag as a GitHub release?

**Comment by remicollet** [comment]
Github release added (as older exist), despite the **authoritative information** should be taken from https://pecl.php.net/package/memcached

git is only used for sources management (and I personally try to avoid as much as possible using github specific features, as the switch to any other forge will imply to loose everything)
