### ISSUE TITLE
php8.1 int is not int

### ISSUE THREAD

**Issue by Krakozaber** [php-memcached-dev/php-memcached#496]
Memcached::setMulti(): Argument #2 ($expiration) must be of type int, int given

**Comment by LordSimal** [comment]
See https://github.com/php-memcached-dev/php-memcached/issues/484
It seems that this has already been "fixed" but no release has been tagged since 2019

**Comment by Flo354** [comment]
I don't know if this is fixed either, but there is another issue with int is not int: 

```Memcached::cas(): Argument #4 ($expiration) must be of type int, int given```

**Comment by Krakozaber** [comment]
Is it dead ?

**Comment by mrohnstock** [comment]
well... I'm in the same boat now - would it be possible to finally tag a new version with this fix?

**Comment by Flo354** [comment]
I ended up compiling by myself the extension for PHP 8.1...

Only reliable solution for now...

**Comment by devanych** [comment]
Yes, using the extension in PHP 8.1, there are some "terrible" errors :sleepy:
https://github.com/yiisoft/cache-memcached/runs/4954577582?check_suite_focus=true

**Comment by wucdbm** [comment]
So do we just dump this and migrate to Redis instead?!

**Comment by tillkruss** [comment]
The `memcache` and `redis` extension are maintained: https://pecl.php.net/package/memcache

**Comment by cmb69** [comment]
memcached 3.2.0RC1 and 3.2.0RC2 have been released today. I assume this ticket can be closed.

**Comment by remicollet** [comment]
indeed
