### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by ckhatton** [php-memcached-dev/php-memcached#514]
Hi there

How does one build from source? I tried the build instructions in the readme, and it gave the error...

```
The program 'phpize' is currently not installed. You can install it by typing:
sudo apt install php7.0-dev
```

I am currently using PHP 8.0.5.
Ubuntu 16.04.7 EMS

**Comment by paxter** [comment]
Check out your php/bin folder. There should be a `phpize` binary which you need for that.

**Comment by sodabrew** [comment]
@ckhatton Ok to close this issue?
