### ISSUE TITLE
Incorrect PHP reflection type for Memcached::cas $cas_token

### ISSUE THREAD

**Issue by gdejong** [php-memcached-dev/php-memcached#523]
The first argument (`$cas_token`) to `Memcached::cas` is a `float` according to the [documentation](https://www.php.net/manual/en/memcached.cas.php).

![image](https://user-images.githubusercontent.com/2346366/201494857-7d577b69-1f5e-460a-95d4-5280bbedc5d1.png)

However when using Reflection to list the parameters it determines that the `$cas_token` is of type `string`.

PHP script:
```
<?php
declare(strict_types=1);

$class = Memcached::class;
$method_to_inspect = "cas";

$method = new ReflectionMethod($class, $method_to_inspect);

echo "PHP version: " . PHP_VERSION . PHP_EOL;
echo "memcached version: " . phpversion("memcached") . PHP_EOL;
echo "Reflecting $class::$method_to_inspect" . PHP_EOL;


foreach ($method->getParameters() as $parameter) {
    echo "-  " . $parameter->getDeclaringClass()->getName() . "::" . $parameter->getName() . PHP_EOL;
    echo "   " . "type: " . $parameter->getType()->getName() . PHP_EOL;
}
```

results in
```
PHP version: 8.1.12
memcached version: 3.2.0
Reflecting Memcached::cas
-  Memcached::cas_token
   type: string
-  Memcached::key
   type: string
-  Memcached::value
   type: mixed
-  Memcached::expiration
   type: int
```

Dockerfile:
```
FROM php:8.1-cli-alpine

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && install-php-extensions memcached

```

Where does this inconsistency come from and can it be resolved?

A possible explanation is https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.stub.php#L34
This stub file type hints the `$cas_token` parameter as being a `string`.

```
public function cas(string $cas_token, string $key, mixed $value, int $expiration=0): bool {}
```

**Comment by remicollet** [comment]
According to the code, the `$cas_token` should be an unsigned 64-bit integer (library side). In the extension valid type are **integer, float and string** (converted to `uint64_t`), but all type are accepted (so mixed).
