### ISSUE TITLE
Release 3.2.1

### ISSUE THREAD

**Issue by remicollet** [php-memcached-dev/php-memcached#525]
I propose to release a new bugfix version 3.2.1

Changelog:

* mark password as a sensitive param for 8.2 
* Fix gh#523 Incorrect PHP reflection type for Memcached::cas $cas_token

**Comment by bert126** [comment]
Are you going to include libmemcached-awesome 1.1.3 in it?

**Comment by remicollet** [comment]
@bert126 this is out of topic here, rather a downstream (binary provider) issue.

**Comment by lifenglsf** [comment]
#528 ，windows 8.2 编译需要合并下这个pull request，不然8.2windows会编译失败的

**Comment by sodabrew** [comment]
Anything else folks want to get in here? I think we could roll a new version at this time.

**Comment by hydrapolic** [comment]
Hello, would be nice to release 3.2.1 with php 8.2 support, I'd love to add it to Gentoo Linux ;) 

Thanks!

**Comment by lifenglsf** [comment]
any news?

**Comment by lianglee** [comment]
No news =D

**Comment by m6w6** [comment]
Since there was already a lot more committed, that usual for a patch release I tossed together even more for a 3.3.0RC1.
@remicollet do you want to add more, or are we (you) ready to do the release dance? 🎉

**Comment by remicollet** [comment]
> Since there was already a lot more committed, that usual for a patch release I tossed together even more for a 3.3.0RC1.

+1

> @remicollet do you want to add more, or are we (you) ready to do the release dance? 🎉

Nothing to add, just thinking about minimal supported version (7.0 for now)

Perhaps we could raise to 7.4 and move everything to PKG_CHECK_MODULES
But as this is a long avaiting version, can be differed to later (3.4)

Using PHP 8.4.0RC1 and 3.3.0RC1 test suite passes

So I'm fine for a 3.3.0RC1

As I'm overwhelmed I won't be able to manage it before a few days

@m6w6 perhaps you should add you as "lead" in the package.xml and I can add you to pecl (for your 1st upload) ?

**Comment by m6w6** [comment]
Final commit and tag pushed. Waiting for PECL rights :+1:

**Comment by remicollet** [comment]
> Final commit and tag pushed. Waiting for PECL rights 👍

done, see https://pecl.php.net/package/memcached
