### ISSUE TITLE
Support for PHP 8.1.7

### ISSUE THREAD

**Issue by bert126** [php-memcached-dev/php-memcached#527]
Are you planning to support PHP 8.1.7 soon?

3.2.0 is working well under our PHP 7.x and PHP 8.1.0 Windows servers but it's impossible to make it work under PHP 8.1.7 (Unable to load dynamic library - The specified module could not be found).

Same behavior on DEVs machines.

**Comment by bert126** [comment]
I wonder if it might be a problem with the underlying libmemcached.dll. 
Does it have to be installed in a specific way (regsrv32) on Windows?

**Comment by bert126** [comment]
I got it. the two DLLs (libmemcached.dll and libhashkit.dll) must be copied under c:\windows.
Might be useful to specify it in the readme for the next ones

**Comment by sodabrew** [comment]
I generally wouldn't recommend putting all of your application DLLs into the Windows dir. You can set the DLLPATH for your web server application to an appropriate deployment directory. 

Here is some documentation that may help: https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

**Comment by bert126** [comment]
You are right! I will tell my sysadmin to create a dedicated directory and add it to the %PATH%
