### ISSUE TITLE
Use memcache on wordpress with php 8.1

### ISSUE THREAD

**Issue by rubo77** [php-memcached-dev/php-memcached#536]
I tried the  "Memcached Object Cache" Plugin, but it seems not to run on php 8.1, see https://unix.stackexchange.com/questions/742587

How do I enable memcache in Wordpress on PHP 8.1?

**Comment by sodabrew** [comment]
That howto describes using the "memcache" module, which has not been updated in years. Please use the "memcached" module (note the final letter "d") which is this project and fully supports PHP 8.x

**Comment by rubo77** [comment]
I tried to install the module with "d" but failed.

I installed Redis now instead, see: https://unix.stackexchange.com/a/743405/20661
