### ISSUE TITLE
Installing in docker, with apache + php-7.4 | GC_REFCOUNT

### ISSUE THREAD

**Issue by rapttor** [php-memcached-dev/php-memcached#537]
version 7.1, 7.3 was working ok, switching to 7.4 produces this error: 

#0 7.951 /bin/bash /usr/src/php/ext/memcached/libtool --mode=compile cc -I/usr/local/include/php    -I. -I/usr/src/php/ext/memcached -DPHP_ATOM_INC -I/usr/src/php/ext/memcached/include -I/usr/src/php/ext/memcached/main -I/usr/src/php/ext/memcached -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib   -c /usr/src/php/ext/memcached/php_memcached.c -o php_memcached.lo 
#0 8.128 mkdir .libs
#0 8.132  cc -I/usr/local/include/php -I. -I/usr/src/php/ext/memcached -DPHP_ATOM_INC -I/usr/src/php/ext/memcached/include -I/usr/src/php/ext/memcached/main -I/usr/src/php/ext/memcached -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -c /usr/src/php/ext/memcached/php_memcached.c  -fPIC -DPIC -o .libs/php_memcached.o
#0 8.251 /usr/src/php/ext/memcached/php_memcached.c: In function 'zim_Memcached___construct':
#0 8.252 /usr/src/php/ext/memcached/php_memcached.c:1282:20: error: lvalue required as left operand of assignment
#0 8.252  1282 |   GC_REFCOUNT(&le) = 1;
#0 8.252       |                    ^
#0 8.284 make: *** [Makefile:192: php_memcached.lo] Error 1

**Comment by sodabrew** [comment]
Which version of php-memcached are you starting this with? Double check that you're using the most recent version.

**Comment by rapttor** [comment]
tried with latest (i think so) 

RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p /usr/src/php/ext/memcached \
    && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && docker-php-ext-configure memcached \
    && docker-php-ext-install memcached \
    && rm /tmp/memcached.tar.gz

**Comment by sodabrew** [comment]
> https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz
> 

That’s extremely old! The master branch releases fully support PHP 7.x and 8.x as noted in the README file. Please begin using the latest version as released.
