### ISSUE TITLE
No updated DLL version available 

### ISSUE THREAD

**Issue by dfumagalli** [php-memcached-dev/php-memcached#544]
I have installed a recent PHP 8.2 build.
Everything works except the Memcached Win 64 DLL. Apparently, the latest compiled release available on the PECL page, [3.2.0](https://pecl.php.net/package/memcached/3.2.0/windows), does not work with PHP 8.2, despite this GitHub repo saying so.

Here's what the log says:

`[16-Oct-2023 19:18:50 UTC] PHP Warning:  PHP Startup: memcached: Unable to initialize module

Module compiled with module API=20210902

PHP    compiled with module API=20220829

These options need to match

 in Unknown on line 0`

Sadly I cannot fix this issue by myself. Please issue a new compiled version.

**Comment by lianglee** [comment]
Same issue not showing in phpinfo either,  php starts without issue but memcached section not showing. Same error :

Warning: PHP Startup: memcached: Unable to initialize module
Module compiled with module API=20210902
PHP    compiled with module API=20220829
These options need to match

**Comment by macintoshplus** [comment]
I am pleased to announce that this extension is now compiled for Windows by the PHP Extension Repository site.

You can download the DLLs on the extension page: https://phpext.phptools.online/extension/caching/memcached-19

If you have any questions, I am available to discuss them.

**Comment by m6w6** [comment]
Fixed at the PECL website.
