### ISSUE TITLE
Unable to load dynamic library 'memcached' on Windows

### ISSUE THREAD

**Issue by Markshall** [php-memcached-dev/php-memcached#563]
Hi,

I'm running on Windows 11 using PHP 8.3.12.

I am trying to add the php_memcached.dll library (php ts x64) to my install but I get the following error:

```bash
Warning: PHP Startup: Unable to load dynamic library 'memcached' (tried: c:/wamp64/bin/php/php8.3.12/ext/memcached (The specified module could not be found), c:/wamp64/bin/php/php8.3.12/ext/php_memcached.dll (The specified module could not be found)) in Unknown on line 0
```

The file exists in my ext directory, and I have placed libmemcached.dll in both `c:/wamp64/bin/php/php8.3.12/` and `c:/wamp64/bin/php/php8.3.12/ext/` but still to no avail.

I am at a loss for what I seem to be doing wrong.

**Comment by m6w6** [comment]
AFAICS, there are a lot more DLLs in that package. Did you put all of them in the same directory?

**Comment by Markshall** [comment]
Well that's embarrassing, Windows was grouping the files by date, 'earlier this year', 'a long time ago' etc. and I hadn't noticed so was only copying the main php_memcached.dll file. Thanks!

**Comment by muffetlab** [comment]
I've been struggling with this issue for several days. Finally, it worked! Here is what I did:
1. Copy php_memcached.dll to {PHP_DIR}/ext/
2. Copy all other DLL files to  {PHP_DIR}/
3. Restart Apache.

**Comment by ve3** [comment]
I have the same problem. Fix as suggested by @muffetlab  works.

More details:

I'm using Apache with build with **Visual C++ 2022** & Thread Safety disabled.  
Server API is **CGI/FastCGI**.

I copy all files in ZIP to a folder for example **D:\mywww-server\memcached\php8.5**.    
Now in Apache config, I add path to virtual host config file.  
Example:
```
<VirtualHost *:443>
    FcgidInitialEnv PATH "${WWWSERVER}/php/php8.5;D:/mywww-server/memcached/php8.5;C:/WINDOWS/system32;C:/WINDOWS;C:/WINDOWS/System32/Wbem;"
</VirtualHost>
```

Restart web server, kill PHP processes and start browsing. Everything (almost) back to work. 
The rest of problem is same as other issue (session support is no).

**Comment by saad-ka** [comment]
I had the same problem (Wamp on windows) tried @muffetlab fix but still not working so I did another step and it worked:
 Copy all other DLL files to {APACHE_DIR}\bin\
