### ISSUE TITLE
increment can't bigger than 4294967295

### ISSUE THREAD

**Issue by eibisee** [php-memcached-dev/php-memcached#58]
$o = new Memcached();
$o->addServers( array(
    array('127.0.0.1', 11211, 100)
));
$o->set('ddd', 0, 0);

$x = $o->increment('ddd', 4294967295);  //OK
$x = $o->increment('ddd', 4294967296);  //Error.

system  is 64Bit.

**Comment by sodabrew** [comment]
Confirmed this is still a bug in 3.0.0 with PHP 7.0 and PHP 7.1.

**Comment by sodabrew** [comment]
Ah, the _value_ can be 64-bit, but the _increment_ is limited to 32-bits per API call. The protocol does allow 64-bit increments, so it might only be an API issue in libmemcached: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L274

**Comment by mhagstrand** [comment]
The problem still exists in the libmemcached: 
http://bazaar.launchpad.net/~tangent-trunk/libmemcached/1.2/view/head:/libmemcached/auto.cc#L149

It is possible to work around this problem by replacing `memcached_increment` with `memcached_increment_by_key` in the code below.
https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c#L2224

That would look something like this:
```
    if (by_key) {
      if (incr) {
        status = memcached_increment_by_key(intern->memc, ZSTR_VAL(server_key), ZSTR_LEN(server_key), ZSTR_VAL(key), ZSTR_LEN(key), (unsigned int)offset, &value);
      } else {
        status = memcached_decrement_by_key(intern->memc, ZSTR_VAL(server_key), ZSTR_LEN(server_key), ZSTR_VAL(key), ZSTR_LEN(key), (unsigned int)offset, &value);
      }
    } else {
      if (incr) {
        status = memcached_increment_by_key(intern->memc, ZSTR_VAL(key), ZSTR_LEN(key), ZSTR_VAL(key), ZSTR_LEN(key), (unsigned int)offset, &value);
      } else {
        status = memcached_decrement_by_key(intern->memc, ZSTR_VAL(key), ZSTR_LEN(key), ZSTR_VAL(key), ZSTR_LEN(key), (unsigned int)offset, &value);
      }
    }
```

**Comment by sodabrew** [comment]
The documentation is mis-matched to the actual code! Yes, memcached_increment_by_key accepts a 64-bit offset. This should be straightforward to fix in the master branch.

**Comment by mhagstrand** [comment]
I can put together a PR if you want or you can take care of it if you want.

**Comment by sodabrew** [comment]
Thanks for the offer! I've got it going in #306
