### ISSUE TITLE
increment function adds white space to value

### ISSUE THREAD

**Issue by shades88** [php-memcached-dev/php-memcached#62]
memcached-server - 1.4.5
php-memcached - 2.0.1
libmemcached    - 1.0.8
php                    - 5.3.6

When I increment a key using default value, it's size is shown as 22 in telnet interface. Subsequent increments add white-spaces to the value. 
Here's the code:

$bucketOps = new Memcached();
$bucketOps->setOption(Memcached::OPT_BINARY_PROTOCOL, true);
$bucketOps->addServer('10.90.15.104', 11211);
$bucketOps->addServer('10.90.15.104', 11311);

$bucketOps->set('foo2', 'bar2');
$bucketOps->increment('sample-cnt', 1, 1);

Here's how it looks in telnet

get sample-cnt
VALUE sample-cnt 0 22
1END

Notice the size of the value. Then I run the code again, so this time it should increment the value to 2. It does that but here's how it looks in telnet again

get sample-cnt
VALUE sample-cnt 0 22
2                     END

Notice the white spaces between the value and END.
I don't know why this is happening. Please help

**Comment by sodabrew** [comment]
This looks like an old memcached bug fixed in memcached server version 1.4.17
https://github.com/memcached/memcached/wiki/ReleaseNotes1417#fixes
