### ISSUE TITLE
Windows Binary

### ISSUE THREAD

**Issue by olekukonko** [php-memcached-dev/php-memcached#71]
Hello,

Obviously so may people are looking for the windows binary version of memcached 
- http://stackoverflow.com/questions/16023165/is-there-a-php-memcached-dll-extension
- http://stackoverflow.com/questions/1451090/where-can-i-find-php-memcached-dll-php-extension
- http://stackoverflow.com/questions/9693195/does-memcached-dll-exist

Is it possible to also make windows binary version for `PHP 5..3` and `PHP 5.4` available at  http://windows.php.net/downloads/pecl/releases/ ?

**Comment by oroszlanyzsolt** [comment]
I quote joelhy comment from PHP.net memcached page:

> For those confuse about the memcached extension and the memcache extension, the short story
> is that both of them are clients of memcached server, and the memcached extension offer more 
> features than the memcache extension.
