### ISSUE TITLE
Close unused persistent memcached connections after specified timeout.

### ISSUE THREAD

**Issue by arjenschol** [php-memcached-dev/php-memcached#73]
Persistent connections to memcached appear to be only closed when apache/php-fpm 
is restarted.

Our persistent identifier is based on the application version, so old data for 
some caches is automagically expired. However, the old persistent connections 
won't be closed and keeps lots of unused tcp connections open.
## Test script:

<?php
for ($i = 0; $i < 10000; $i++)
$m = new Memcached('persistent' . $i);
## Expected result:

Unused persistent connections should be closed after a configurable timeout.

**Comment by sodabrew** [comment]
libmemcached handles the underlying connections for us, and there are no options for terminating connections to idle backend servers: http://docs.libmemcached.org/memcached_behavior.html
