### ISSUE TITLE
Buffer writes not working as expected

### ISSUE THREAD

**Issue by entering** [php-memcached-dev/php-memcached#78]
Memcached::OPT_BUFFER_WRITES
Enables or disables buffered I/O. Enabling buffered I/O causes storage commands to "buffer" instead of being sent. **Any action that retrieves data causes this buffer to be sent to the remote connection**. Quitting the connection or closing down the connection will also cause the buffered data to be pushed to the remote connection.

Type: boolean, default: FALSE.

@ http://php.net/manual/en/memcached.constants.php

``` php
$ php -a
Interactive shell

php > $m = new \Memcached(); $m->addServer('....', 11211);
php > $m->set('test1', 10);
php > var_dump($m->get('test1'));
int(10)
php > $m->setOption(\Memcached::OPT_BUFFER_WRITES, true);
php > $m->set('test2', 20);
php > var_dump($m->get('test2'));
bool(false)
php > var_dump($m->getResultMessage());
string(9) "NOT FOUND"
```

I don't understand why there isn't a method like flush buffers, is already implemented at libmemcached:

http://docs.libmemcached.org/memcached_flush_buffers.html

**Comment by sodabrew** [comment]
It's been a few years, can this issue be closed now? Is it resolved or wont-fix or still a problem?
