### ISSUE TITLE
Segfault when re-adding server after resetServerList() and using DISTRIBUTION=CONSISTENT

### ISSUE THREAD

**Issue by arjenschol** [php-memcached-dev/php-memcached#79]
Testscript and backtrace @ https://gist.github.com/arjenschol/5729158

**Comment by sodabrew** [comment]
Closing because this was verified as a bug in libmemcached.

**Comment by ukautz** [comment]
If somebody else stumbles across this: I am experiencing this exact issue with libmemached 1.0.18. It's not a php-memcached bug, for sure. 

**How to fix**: In the above mentioned Launchpad page the ["continuum patch" linked](https://bugs.launchpad.net/libmemcached/+bug/1154159/+attachment/4273289/+files/patch-continuum.diff), which fixes the issue as far as I can tell. It's not part of the official version 1.0.18, though.
