### ISSUE TITLE
Casting cas_token to double fails for large cas values

### ISSUE THREAD

**Issue by tachu** [php-memcached-dev/php-memcached#82]
Given a key with a cas_token value of 9941891035036819 the cas operation will fail as casting the cas_token to double will round it up to 9941891035036820.

We tested casting the cas_token to long and was sucesful in casing the value in memcached. 

Running php 5.3.24 
memcached support => enabled
Version => 1.0.2
libmemcached version => 0.44
Session support => yes

sample code

printf("cas %ld, dbl cas: %f\n", 9941891035036819, (double)9941891035036819);

**Comment by sodabrew** [comment]
This is fixed in the upcoming 3.0.0 release.
